ALTER TABLE "food_items"
ADD COLUMN "saturated_fat" DOUBLE PRECISION,
ADD COLUMN "trans_fat" DOUBLE PRECISION,
ADD COLUMN "cholesterol" DOUBLE PRECISION,
ADD COLUMN "sodium" DOUBLE PRECISION,
ADD COLUMN "potassium" DOUBLE PRECISION,
ADD COLUMN "dietary_fiber" DOUBLE PRECISION,
ADD COLUMN "sugars" DOUBLE PRECISION,
ADD COLUMN "vitamin_a" DOUBLE PRECISION,
ADD COLUMN "vitamin_c" DOUBLE PRECISION,
ADD COLUMN "calcium" DOUBLE PRECISION,
ADD COLUMN "iron" DOUBLE PRECISION;
