/**
 * Map Postgres plan rows → legacy API source + dashboard badges.
 */

const BOILERPLATE_COACH_NOTES =
  /safe baseline plan generated automatically|open the chat coach for personalized/i;

const RULES_EXPLAIN =
  /خطة أسبوعية من ملفك|weekly plan from your profile|تمارين ووجبات — يمكن تحسينها/i;

const CLAUDE_EXPLAIN =
  /مخصصة بالذكاء الاصطناعي \(Claude\)|Claude using your profile|Personalized weekly plan from Claude/i;

const SCAFFOLD_EXPLAIN =
  /safe scaffold|scaffold plan|ANTHROPIC_API_KEY|خطة آمنة/i;

function isBoilerplateCoachNotes(text) {
  return BOILERPLATE_COACH_NOTES.test(String(text || ''));
}

/**
 * @param {{ explainabilityText?: string|null, aiNotes?: string|null }} row
 * @returns {'ai'|'fallback'}
 */
function inferLegacySource({ explainabilityText, aiNotes }) {
  const explain = String(explainabilityText || '').trim();
  const notes = String(aiNotes || '').trim();

  if (SCAFFOLD_EXPLAIN.test(explain)) return 'fallback';
  if (CLAUDE_EXPLAIN.test(explain)) return 'ai';
  if (RULES_EXPLAIN.test(explain)) return 'fallback';
  if (!explain && isBoilerplateCoachNotes(notes)) return 'fallback';
  if (/personalized|تخصيص كامل|generated by ai|مولّدة بالذكاء/i.test(explain)) return 'ai';
  if (explain && !RULES_EXPLAIN.test(explain) && !SCAFFOLD_EXPLAIN.test(explain)) return 'ai';
  return 'fallback';
}

/**
 * @param {string|null|undefined} prismaSource
 * @param {string|null|undefined} explainabilityText
 * @returns {'ai'|'rules'|'fallback'|'manual'|null}
 */
function mapDashboardPlanSource(prismaSource, explainabilityText) {
  const explain = String(explainabilityText || '');
  if (CLAUDE_EXPLAIN.test(explain)) return 'ai';
  if (RULES_EXPLAIN.test(explain)) return 'rules';
  if (SCAFFOLD_EXPLAIN.test(explain)) return 'fallback';
  if (prismaSource === 'manual') return 'manual';
  if (prismaSource === 'onboarding') {
    if (inferLegacySource({ explainabilityText: explain, aiNotes: '' }) === 'ai') return 'ai';
    return 'rules';
  }
  return prismaSource || null;
}

module.exports = {
  isBoilerplateCoachNotes,
  inferLegacySource,
  mapDashboardPlanSource,
  RULES_EXPLAIN,
};
