import type { ProductTourStep } from '../../lib/productTour/types';

/** Shared community tour steps (feed → profile → browse → groups → inbox → settings). */
export const communityTourSteps: ProductTourStep[] = [
  {
    id: 'community-tabs',
    route: '/community',
    sectionKey: 'tour.section.community',
    titleKey: 'tour.community.tabsTitle',
    bodyKey: 'tour.community.tabsBody',
    placement: 'bottom',
  },
  {
    id: 'community-composer',
    route: '/community',
    sectionKey: 'tour.section.community',
    titleKey: 'tour.community.composerTitle',
    bodyKey: 'tour.community.composerBody',
    placement: 'bottom',
  },
  {
    id: 'community-feed-tabs',
    route: '/community',
    sectionKey: 'tour.section.community',
    titleKey: 'tour.community.feedTabsTitle',
    bodyKey: 'tour.community.feedTabsBody',
    placement: 'bottom',
  },
  {
    id: 'community-posts',
    route: '/community',
    sectionKey: 'tour.section.community',
    titleKey: 'tour.community.postsTitle',
    bodyKey: 'tour.community.postsBody',
    placement: 'top',
  },
  {
    id: 'community-stories',
    route: '/community',
    sectionKey: 'tour.section.community',
    titleKey: 'tour.community.storiesTitle',
    bodyKey: 'tour.community.storiesBody',
    placement: 'bottom',
  },
  {
    id: 'community-profile-header',
    route: '/community/profile',
    sectionKey: 'tour.section.community',
    titleKey: 'tour.community.profileHeaderTitle',
    bodyKey: 'tour.community.profileHeaderBody',
    placement: 'bottom',
  },
  {
    id: 'community-profile-tabs',
    route: '/community/profile',
    sectionKey: 'tour.section.community',
    titleKey: 'tour.community.profileTabsTitle',
    bodyKey: 'tour.community.profileTabsBody',
    placement: 'bottom',
  },
  {
    id: 'community-browse-search',
    route: '/community/browse',
    sectionKey: 'tour.section.community',
    titleKey: 'tour.community.browseSearchTitle',
    bodyKey: 'tour.community.browseSearchBody',
    placement: 'bottom',
  },
  {
    id: 'community-browse-discover',
    route: '/community/browse',
    sectionKey: 'tour.section.community',
    titleKey: 'tour.community.browseDiscoverTitle',
    bodyKey: 'tour.community.browseDiscoverBody',
    placement: 'top',
  },
  {
    id: 'community-groups-header',
    route: '/community/groups',
    sectionKey: 'tour.section.community',
    titleKey: 'tour.community.groupsHeaderTitle',
    bodyKey: 'tour.community.groupsHeaderBody',
    placement: 'bottom',
  },
  {
    id: 'community-groups-list',
    route: '/community/groups',
    sectionKey: 'tour.section.community',
    titleKey: 'tour.community.groupsListTitle',
    bodyKey: 'tour.community.groupsListBody',
    placement: 'top',
  },
  {
    id: 'community-inbox-header',
    route: '/community/inbox',
    sectionKey: 'tour.section.community',
    titleKey: 'tour.community.inboxHeaderTitle',
    bodyKey: 'tour.community.inboxHeaderBody',
    placement: 'bottom',
  },
  {
    id: 'community-inbox-folders',
    route: '/community/inbox',
    sectionKey: 'tour.section.community',
    titleKey: 'tour.community.inboxFoldersTitle',
    bodyKey: 'tour.community.inboxFoldersBody',
    placement: 'bottom',
  },
  {
    id: 'community-inbox-conversations',
    route: '/community/inbox',
    sectionKey: 'tour.section.community',
    titleKey: 'tour.community.inboxConversationsTitle',
    bodyKey: 'tour.community.inboxConversationsBody',
    placement: 'top',
  },
  {
    id: 'community-settings-privacy',
    route: '/community/settings',
    sectionKey: 'tour.section.community',
    titleKey: 'tour.community.settingsPrivacyTitle',
    bodyKey: 'tour.community.settingsPrivacyBody',
    placement: 'bottom',
  },
];
