import type { ProductTourStep } from '../../lib/productTour/types';
import { gymCommunityTourSteps } from './gymCommunityTourSteps';

/**
 * Gym owner tour — focused steps with compact spotlight targets.
 * Profile → dashboard ops → reception → equipment → community → settings → support → nav.
 */
export const gymAppTourSteps: ProductTourStep[] = [
  // —— Profile ——
  {
    id: 'gym-tour-profile-hero',
    route: '/profile',
    sectionKey: 'tour.section.profile',
    titleKey: 'tour.gym.profileHeroTitle',
    bodyKey: 'tour.gym.profileHeroBody',
    placement: 'bottom',
  },
  {
    id: 'gym-tour-profile-business',
    route: '/profile',
    sectionKey: 'tour.section.profile',
    titleKey: 'tour.gym.profileBusinessTitle',
    bodyKey: 'tour.gym.profileBusinessBody',
    placement: 'bottom',
  },
  {
    id: 'gym-tour-profile-media',
    route: '/profile',
    sectionKey: 'tour.section.profile',
    titleKey: 'tour.gym.profileMediaTitle',
    bodyKey: 'tour.gym.profileMediaBody',
    placement: 'bottom',
  },
  {
    id: 'gym-tour-profile-listing',
    route: '/profile',
    sectionKey: 'tour.section.profile',
    titleKey: 'tour.gym.profileListingTitle',
    bodyKey: 'tour.gym.profileListingBody',
    placement: 'top',
  },
  {
    id: 'gym-tour-profile-location',
    route: '/profile',
    sectionKey: 'tour.section.profile',
    titleKey: 'tour.gym.profileLocationTitle',
    bodyKey: 'tour.gym.profileLocationBody',
    placement: 'top',
  },
  {
    id: 'gym-tour-profile-amenities',
    route: '/profile',
    sectionKey: 'tour.section.profile',
    titleKey: 'tour.gym.profileAmenitiesTitle',
    bodyKey: 'tour.gym.profileAmenitiesBody',
    placement: 'top',
  },
  {
    id: 'gym-tour-profile-save',
    route: '/profile',
    sectionKey: 'tour.section.profile',
    titleKey: 'tour.gym.profileSaveTitle',
    bodyKey: 'tour.gym.profileSaveBody',
    placement: 'top',
  },

  // —— Gym dashboard ——
  {
    id: 'gym-tour-dash-header',
    route: '/owner/dashboard',
    sectionKey: 'tour.section.gymDashboard',
    titleKey: 'tour.gym.dashHeaderTitle',
    bodyKey: 'tour.gym.dashHeaderBody',
    placement: 'bottom',
  },
  {
    id: 'gym-tour-dash-capacity',
    route: '/owner/dashboard',
    sectionKey: 'tour.section.gymDashboard',
    titleKey: 'tour.gym.dashCapacityTitle',
    bodyKey: 'tour.gym.dashCapacityBody',
    placement: 'bottom',
  },
  {
    id: 'gym-tour-dash-kpis',
    route: '/owner/dashboard',
    sectionKey: 'tour.section.gymDashboard',
    titleKey: 'tour.gym.dashKpisTitle',
    bodyKey: 'tour.gym.dashKpisBody',
    placement: 'bottom',
  },
  {
    id: 'gym-tour-dash-class-sessions',
    route: '/owner/dashboard',
    sectionKey: 'tour.section.gymDashboard',
    titleKey: 'tour.gym.dashClassSessionsTitle',
    bodyKey: 'tour.gym.dashClassSessionsBody',
    placement: 'top',
  },
  {
    id: 'gym-tour-dash-checkins',
    route: '/owner/dashboard',
    sectionKey: 'tour.section.gymDashboard',
    titleKey: 'tour.gym.dashCheckinsTitle',
    bodyKey: 'tour.gym.dashCheckinsBody',
    placement: 'top',
  },
  {
    id: 'gym-tour-dash-plan-chart',
    route: '/owner/dashboard',
    sectionKey: 'tour.section.gymDashboard',
    titleKey: 'tour.gym.dashPlanChartTitle',
    bodyKey: 'tour.gym.dashPlanChartBody',
    placement: 'left',
  },
  {
    id: 'gym-tour-dash-plans',
    route: '/owner/dashboard',
    sectionKey: 'tour.section.gymDashboard',
    titleKey: 'tour.gym.dashPlansTitle',
    bodyKey: 'tour.gym.dashPlansBody',
    placement: 'top',
  },
  {
    id: 'gym-tour-dash-staff',
    route: '/owner/dashboard',
    sectionKey: 'tour.section.gymDashboard',
    titleKey: 'tour.gym.dashStaffTitle',
    bodyKey: 'tour.gym.dashStaffBody',
    placement: 'top',
  },
  {
    id: 'gym-tour-dash-basic-sessions',
    route: '/owner/dashboard',
    sectionKey: 'tour.section.gymDashboard',
    titleKey: 'tour.gym.dashBasicSessionsTitle',
    bodyKey: 'tour.gym.dashBasicSessionsBody',
    placement: 'top',
  },
  {
    id: 'gym-tour-dash-classes',
    route: '/owner/dashboard',
    sectionKey: 'tour.section.gymDashboard',
    titleKey: 'tour.gym.dashClassesTitle',
    bodyKey: 'tour.gym.dashClassesBody',
    placement: 'top',
  },

  // —— Reception ——
  {
    id: 'gym-tour-reception-register',
    route: '/owner/reception',
    sectionKey: 'tour.section.reception',
    titleKey: 'tour.gym.receptionRegisterTitle',
    bodyKey: 'tour.gym.receptionRegisterBody',
    placement: 'bottom',
  },
  {
    id: 'gym-tour-reception-present',
    route: '/owner/reception',
    sectionKey: 'tour.section.reception',
    titleKey: 'tour.gym.receptionPresentTitle',
    bodyKey: 'tour.gym.receptionPresentBody',
    placement: 'bottom',
  },
  {
    id: 'gym-tour-reception-roster',
    route: '/owner/reception',
    sectionKey: 'tour.section.reception',
    titleKey: 'tour.gym.receptionRosterTitle',
    bodyKey: 'tour.gym.receptionRosterBody',
    placement: 'bottom',
  },
  {
    id: 'gym-tour-reception-members',
    route: '/owner/reception',
    sectionKey: 'tour.section.reception',
    titleKey: 'tour.gym.receptionMembersTitle',
    bodyKey: 'tour.gym.receptionMembersBody',
    placement: 'top',
  },
  {
    id: 'gym-tour-reception-detail',
    route: '/owner/reception',
    sectionKey: 'tour.section.reception',
    titleKey: 'tour.gym.receptionDetailTitle',
    bodyKey: 'tour.gym.receptionDetailBody',
    placement: 'left',
  },

  // —— Equipment ——
  {
    id: 'gym-tour-equipment-header',
    route: '/owner/equipment',
    sectionKey: 'tour.section.equipment',
    titleKey: 'tour.gym.equipmentHeaderTitle',
    bodyKey: 'tour.gym.equipmentHeaderBody',
    placement: 'bottom',
  },
  {
    id: 'gym-tour-equipment-add',
    route: '/owner/equipment',
    sectionKey: 'tour.section.equipment',
    titleKey: 'tour.gym.equipmentAddTitle',
    bodyKey: 'tour.gym.equipmentAddBody',
    placement: 'bottom',
  },
  {
    id: 'gym-tour-equipment-list',
    route: '/owner/equipment',
    sectionKey: 'tour.section.equipment',
    titleKey: 'tour.gym.equipmentListTitle',
    bodyKey: 'tour.gym.equipmentListBody',
    placement: 'top',
  },
  {
    id: 'gym-tour-equipment-maintenance',
    route: '/owner/equipment',
    sectionKey: 'tour.section.equipment',
    titleKey: 'tour.gym.equipmentMaintenanceTitle',
    bodyKey: 'tour.gym.equipmentMaintenanceBody',
    placement: 'top',
  },

  ...gymCommunityTourSteps,

  {
    id: 'gym-tour-settings',
    route: '/settings',
    sectionKey: 'tour.section.settings',
    titleKey: 'tour.gym.settingsTitle',
    bodyKey: 'tour.gym.settingsBody',
    placement: 'bottom',
  },
  {
    id: 'gym-tour-support',
    route: '/support',
    sectionKey: 'tour.section.support',
    titleKey: 'tour.gym.supportTitle',
    bodyKey: 'tour.gym.supportBody',
    placement: 'bottom',
  },
  {
    id: 'app-nav',
    sectionKey: 'tour.section.navigation',
    titleKey: 'tour.nav.title',
    bodyKey: 'tour.nav.gymBody',
    placement: 'right',
  },
];
