/** Arabic questionnaire catalog — idempotent upsert by (flow, stepId). */
const ONBOARDING_QUESTION_CATALOG = [
  // ── Core (20) ──
  { flow: 'core', stepId: 'displayName', sortOrder: 1, titleAr: 'ما اسمك؟', reasonAr: 'أول شيء يبني علاقة مع الكوتش؛ خفيف ولا يحتاج تفكير.' },
  { flow: 'core', stepId: 'gender', sortOrder: 2, titleAr: 'ما جنسك؟', reasonAr: 'يخصّص البرنامج واللغة والصور؛ مرتبط بالهوية مباشرة بعد الاسم.' },
  { flow: 'core', stepId: 'age', sortOrder: 3, titleAr: 'كم عمرك؟', reasonAr: 'يحدد شدة التمرين والتعافي؛ رقم بسيط قبل القياسات الجسدية.' },
  { flow: 'core', stepId: 'phone', sortOrder: 4, titleAr: 'ما رقم موبايلك؟', reasonAr: 'تواصل وتحقق الحساب؛ بعد الثقة الأولية، قبل الأسئلة الطويلة.' },
  { flow: 'core', stepId: 'height', sortOrder: 5, titleAr: 'ما طولك؟', reasonAr: 'أساس حساب BMI والسعرات؛ يبدأ «كتلة الجسم» بقياس ثابت.' },
  { flow: 'core', stepId: 'weight', sortOrder: 6, titleAr: 'ما وزنك الحالي؟', reasonAr: 'يكمل الطول لصورة الجسم الحالية قبل الشكل والهدف.' },
  { flow: 'core', stepId: 'weightHistory', sortOrder: 7, titleAr: 'وزنك كان كام من 6 شهور؟', reasonAr: 'بعد الوزن الحالي — يعرف الـ AI إنك ثابت، بتزيد، ولا بتنقص.' },
  { flow: 'core', stepId: 'bodyType', sortOrder: 8, titleAr: 'ما نوع جسمك؟', reasonAr: 'يفسّر سرعة التقدم (نحيف/رياضي/يخزّن) بعد الأرقام.' },
  { flow: 'core', stepId: 'bodyMeasurements', sortOrder: 9, titleAr: 'قياسات الجسم (محيطات)', reasonAr: 'تفصيل اختياري بعد الوزن/الطول؛ لمن يهتم بالتتبع الدقيق.' },
  { flow: 'core', stepId: 'primaryGoal', sortOrder: 10, titleAr: 'ما هدفك الرئيسي؟', reasonAr: 'بعد فهم الجسم نربط «لماذا أنت هنا» — يوجّه كل ما يلي.' },
  { flow: 'core', stepId: 'targetWeight', sortOrder: 11, titleAr: 'الوزن المستهدف', reasonAr: 'يظهر فقط عند «أخسّ» — رقم الهدف الغذائي قبل الموعد النهائي.' },
  { flow: 'core', stepId: 'goalDeadline', sortOrder: 12, titleAr: 'عايز توصل لهدفك إمتى؟', reasonAr: 'أنزل 10 كيلو في 3 شهور ≠ أنزل 10 كيلو في 12 شهر — يحدد وتيرة الخطة.' },
  { flow: 'core', stepId: 'activityLevel', sortOrder: 13, titleAr: 'مستوى نشاطك اليومي', reasonAr: 'يفرّق بين «جالس طول اليوم» و«نشيط» لتقدير السعرات والتعافي.' },
  { flow: 'core', stepId: 'fitnessLevel', sortOrder: 14, titleAr: 'مستواك التدريبي', reasonAr: 'خبرة التمرين وليس النشاط اليومي؛ يحدد صعوبة الخطة.' },
  { flow: 'core', stepId: 'lastTraining', sortOrder: 15, titleAr: 'آخر تمرين / خلفيتك', reasonAr: 'يوضح إنك مبتدئ حقيقي أم راجع بعد فترة.' },
  { flow: 'core', stepId: 'otherSports', sortOrder: 16, titleAr: 'رياضات أخرى', reasonAr: 'تؤثر على التعافي والجدول؛ بعد صورة اللياقة العامة.' },
  { flow: 'core', stepId: 'upcomingEvent', sortOrder: 17, titleAr: 'مناسبة قريبة؟', reasonAr: 'نوع المناسبة + التاريخ — فرح بعد ٤٠ يوم ≠ بعد ٨ شهور.' },
  { flow: 'core', stepId: 'planFailed', sortOrder: 18, titleAr: 'هل فشلت خطط من قبل؟', reasonAr: 'أسباب الفشل (وقت، التزام، دايت…) — من أقوى إشارات للكوتش.' },
  { flow: 'core', stepId: 'inbodyScan', sortOrder: 19, titleAr: 'InBody', reasonAr: 'قياس موضوعي؛ بعد الأساسيات، وقبل/مع الصور.' },
  { flow: 'core', stepId: 'progressPhotos', sortOrder: 20, titleAr: 'صور أمام وجانب وخلف', reasonAr: 'الجانبية أفضل لتقييم الخصر والصدر والوضعية.' },

  // ── Workout (22) ──
  { flow: 'workout', stepId: 'injuries', sortOrder: 1, titleAr: 'إصابات؟', reasonAr: 'أولاً للأمان — كل التمارين تُبنى حول ما يجب تجنبه.' },
  { flow: 'workout', stepId: 'bodyFocus', sortOrder: 2, titleAr: 'مناطق التركيز', reasonAr: 'يخصّص التمارين داخل هدف الـ ١٢ أسبوع.' },
  { flow: 'workout', stepId: 'trainingDaysPerWeek', sortOrder: 3, titleAr: 'أيام التمرين/أسبوع', reasonAr: 'يحدد الحجم (٣ vs ٥ أيام) قبل المكان والوقت.' },
  { flow: 'workout', stepId: 'workoutLocation', sortOrder: 4, titleAr: 'مكان التمرين', reasonAr: 'بيت/جيم يغيّر نوع التمارين بالكامل.' },
  { flow: 'workout', stepId: 'gymLink', sortOrder: 5, titleAr: 'ربط الصالة (إن جيم)', reasonAr: 'يعتمد على اختيار «جيم» في السطر السابق.' },
  { flow: 'workout', stepId: 'workoutTime', sortOrder: 6, titleAr: 'وقت التمرين المفضل', reasonAr: 'يرتبط بالجدول اليومي بعد معرفة الأيام والمكان.' },
  { flow: 'workout', stepId: 'workoutDuration', sortOrder: 7, titleAr: 'مدة التمرينة', reasonAr: 'يحدد حجم كل جلسة بعد معرفة متى تتمرن.' },
  { flow: 'workout', stepId: 'trainingObstacle', sortOrder: 8, titleAr: 'أكبر عائق للتمرين؟', reasonAr: 'بعد الجدول — يوجّه أوضاع الحياة وتعديلات الأسبوع (سفر، وقت، ألم…).' },
  { flow: 'workout', stepId: 'preferredSplit', sortOrder: 9, titleAr: 'تقسيمة/جدول معين؟', reasonAr: 'تفضيل هيكل الأسبوع بعد معرفة العائق والوقت والمدة.' },
  { flow: 'workout', stepId: 'exercisesAvoid', sortOrder: 10, titleAr: 'تمارين ممنوعة', reasonAr: 'قيود شخصية قبل اختبار القوة.' },
  { flow: 'workout', stepId: 'exercisesLove', sortOrder: 11, titleAr: 'تمارين مفضلة', reasonAr: 'نضيف ما يحبه بعد ما استبعدنا ما يكرهه.' },
  { flow: 'workout', stepId: 'pushups', sortOrder: 12, titleAr: 'ضغط', reasonAr: 'اختبارات بسيطة بدون معدات.' },
  { flow: 'workout', stepId: 'squats', sortOrder: 13, titleAr: 'سكوات', reasonAr: 'يكمل صورة الجسم العلوي/السفلي.' },
  { flow: 'workout', stepId: 'pullups', sortOrder: 14, titleAr: 'عقلة', reasonAr: 'يقيّم قوة السحب (غالباً أصعب من الضغط).' },
  { flow: 'workout', stepId: 'benchMax', sortOrder: 15, titleAr: 'بنش (اختياري)', reasonAr: 'يحتاج جيم/بار؛ بعد تمارين وزن الجسم.' },
  { flow: 'workout', stepId: 'deadliftMax', sortOrder: 16, titleAr: 'ديدليفت (اختياري)', reasonAr: 'تقييم متقدم؛ آخر الاختبارات الاختيارية.' },
  { flow: 'workout', stepId: 'addCardio', sortOrder: 17, titleAr: 'إضافة كارديو؟', reasonAr: 'قرار عام قبل تفاصيل الأجهزة.' },
  { flow: 'workout', stepId: 'equipment', sortOrder: 18, titleAr: 'أجهزة كارديو', reasonAr: 'فقط إن قال نعم — لا نزعج من لا يريد كارديو.' },
  { flow: 'workout', stepId: 'strengthEquipment', sortOrder: 19, titleAr: 'معدات القوة', reasonAr: 'تفصيل الجيم بعد الكارديو؛ لبناء الجدول النهائي.' },
  { flow: 'workout', stepId: 'goal12WeekPace', sortOrder: 20, titleAr: 'شدة الهدف لـ ١٢ أسبوع', reasonAr: 'بدونها الـ AI يخمّن حجم التقدم (سريع / متوازن / هادئ).' },
  { flow: 'workout', stepId: 'restDaysPreference', sortOrder: 21, titleAr: 'أيام راحة ثابتة؟', reasonAr: 'يمنع جدول ٦ أيام لمن لا يتحمل — أو «الكوتش يحدد».' },
  { flow: 'workout', stepId: 'liftExperience', sortOrder: 22, titleAr: 'خبرة بتمارين معينة', reasonAr: 'الأرقام لوحدها مش كفاية (مثلاً: أول مرة ديدليفت؟).' },

  // ── Diet (19 + extras from spec) ──
  { flow: 'diet', stepId: 'foodAllergies', sortOrder: 1, titleAr: 'حساسية أكل؟', reasonAr: 'قيود صحية أولاً — لا نعرض أصلاً ما يضرّه.' },
  { flow: 'diet', stepId: 'foodsExcluded', sortOrder: 2, titleAr: 'أكل مرفوض نهائياً؟', reasonAr: 'تفضيل شخصي بعد الحساسية الطبية.' },
  { flow: 'diet', stepId: 'dietType', sortOrder: 3, titleAr: 'نوع الدايت', reasonAr: 'إطار عام (هاي بروتين، لو كارب…) بعد القيود.' },
  { flow: 'diet', stepId: 'mealPlanStyle', sortOrder: 4, titleAr: 'ثابت أسبوعي أم متغير يومياً؟', reasonAr: 'شكل الخطة قبل عدد الوجبات والمكونات.' },
  { flow: 'diet', stepId: 'mealsPerDay', sortOrder: 5, titleAr: 'عدد الوجبات والسناكس', reasonAr: 'يحدد توزيع السعرات على وجبات وسناكس اليوم.' },
  { flow: 'diet', stepId: 'proteinPrefs', sortOrder: 6, titleAr: 'بروتينات مفضلة', reasonAr: 'بناء القائمة يبدأ بالبروتين (أساس العضلات).' },
  { flow: 'diet', stepId: 'carbPrefs', sortOrder: 8, titleAr: 'كارب مفضل', reasonAr: 'ثاني ماكرو للطاقة والتمرين.' },
  { flow: 'diet', stepId: 'fatPrefs', sortOrder: 9, titleAr: 'دهون صحية', reasonAr: 'يكمل الماكروز الثلاثة.' },
  { flow: 'diet', stepId: 'fruitPrefs', sortOrder: 10, titleAr: 'فواكه', reasonAr: 'تفضيلات فرعية بعد الأساسيات.' },
  { flow: 'diet', stepId: 'dairyPrefs', sortOrder: 11, titleAr: 'ألبان', reasonAr: 'نفس المستوى — تفضيلات إضافية.' },
  { flow: 'diet', stepId: 'water', sortOrder: 12, titleAr: 'شرب المية', reasonAr: 'عادة يومية عامة.' },
  { flow: 'diet', stepId: 'eatingHabits', sortOrder: 13, titleAr: 'عادات الأكل', reasonAr: 'سلوك (عاطفي، ملل…) يؤثر على الالتزام.' },
  { flow: 'diet', stepId: 'weekendEating', sortOrder: 14, titleAr: 'أكل الويك إند', reasonAr: 'فرق السلوك السبت/الأحد — سبب شائع لفشل الدايت.' },
  { flow: 'diet', stepId: 'supplementsBudget', sortOrder: 15, titleAr: 'مكملات', reasonAr: 'اختياري — يوضح المكملات الحالية فقط.' },
  { flow: 'diet', stepId: 'foodBudget', sortOrder: 16, titleAr: 'ميزانية الأكل', reasonAr: 'يمنع خطط بسلمون كل يوم لكل الناس (منخفضة / متوسطة / عالية).' },
  { flow: 'diet', stepId: 'eatingOutFrequency', sortOrder: 17, titleAr: 'أكل برّه / دليفري', reasonAr: 'يحدد واقعية الخطة — وجبات جاهزة vs مطبخ.' },
  { flow: 'diet', stepId: 'preferSimpleMeals', sortOrder: 18, titleAr: 'وجبات بسيطة؟', reasonAr: 'تبسيط التعقيد قبل وقت التحضير وطبخ/جاهز.' },
  { flow: 'diet', stepId: 'mealPrepTime', sortOrder: 19, titleAr: 'وقت تحضير الأكل', reasonAr: 'نطاقات واقعية (٠–١٥ / ١٥–٣٠ / ٣٠–٦٠ / ساعة+).' },
  { flow: 'diet', stepId: 'cookOrReady', sortOrder: 20, titleAr: 'هل تطبخ أم تأكل جاهز؟', reasonAr: 'شكل الوجبات.' },
  { flow: 'diet', stepId: 'religiousDiet', sortOrder: 21, titleAr: 'قيود دينية أو ثقافية', reasonAr: 'حلال، رمضان، صيام مسيحي، نباتي صارم — أو لا.' },
  // ── Wellness (12) ──
  { flow: 'wellness', stepId: 'medicalHistory', sortOrder: 1, titleAr: 'تاريخ مرضي', reasonAr: 'أوسع من «إصابة حالية» — يحتاج ثقة وتركيز.' },
  { flow: 'wellness', stepId: 'medications', sortOrder: 2, titleAr: 'أدوية حالية', reasonAr: 'تؤثر على وزن، ضغط، تمرين — بعد التشخيصات.' },
  { flow: 'wellness', stepId: 'pastInjuriesHistory', sortOrder: 3, titleAr: 'إصابات سابقة', reasonAr: 'تاريخ قد يعود؛ مختلف عن إصابات الجدول الحالي.' },
  { flow: 'wellness', stepId: 'doctorClearance', sortOrder: 4, titleAr: 'موافقة طبية', reasonAr: 'يظهر فقط إن لزم بعد معرفة الحالة.' },
  { flow: 'wellness', stepId: 'sleep', sortOrder: 5, titleAr: 'ساعات النوم', reasonAr: 'عادة يومية تؤثر على التعافي والجوع.' },
  { flow: 'wellness', stepId: 'recoveryFeel', sortOrder: 6, titleAr: 'التعافي بعد التمرين', reasonAr: 'يحدد حجم التمرين وأيام الراحة — بعد النوم مباشرة.' },
  { flow: 'wellness', stepId: 'stressLevel', sortOrder: 7, titleAr: 'مستوى الضغط النفسي', reasonAr: '١–١٠؛ مهم للتعافي والالتزام.' },
  { flow: 'wellness', stepId: 'energyLevel', sortOrder: 8, titleAr: 'متوسط الطاقة اليومية', reasonAr: '١–١٠؛ يوجّه شدة التمرين.' },
  { flow: 'wellness', stepId: 'dailyRoutine', sortOrder: 9, titleAr: 'طبيعة اليوم', reasonAr: 'مكتب / واقف / بدني / طالب — للخطة اليومية.' },
  { flow: 'wellness', stepId: 'progressTracking', sortOrder: 10, titleAr: 'كيف تلاحظ التقدم؟', reasonAr: 'أسلوبك في المتابعة (مرآة، ميزان…).' },
  { flow: 'wellness', stepId: 'hungerScale', sortOrder: 11, titleAr: 'الجوع ١–١٠', reasonAr: 'يربط المشاعر بالأكل؛ بعد الأهداف العاطفية.' },
  { flow: 'wellness', stepId: 'motivationStart', sortOrder: 12, titleAr: 'لماذا بدأت؟', reasonAr: 'دافع أساسي — يفتح المحادثة النفسية بلطف.' },
  // ── Wellness — female health (optional, female athletes) ──
  { flow: 'wellness', stepId: 'femaleHealthIntro', sortOrder: 13, titleAr: 'صحة المرأة — اختياري', reasonAr: 'خاص واختياري — يمكن التخطي والتعديل لاحقاً.' },
  { flow: 'wellness', stepId: 'cycleRegularity', sortOrder: 14, titleAr: 'انتظام الدورة', reasonAr: 'اختياري — الطاقة والتعافي.' },
  { flow: 'wellness', stepId: 'cycleSymptoms', sortOrder: 15, titleAr: 'أعراض الدورة', reasonAr: 'اختياري — ليس تشخيصاً.' },
  { flow: 'wellness', stepId: 'pregnancyStatus', sortOrder: 16, titleAr: 'حمل حالي؟', reasonAr: 'علم أمان — موافقة طبية.' },
  { flow: 'wellness', stepId: 'postpartumStatus', sortOrder: 17, titleAr: 'ما بعد الولادة؟', reasonAr: 'علم أمان — عودة تدريجية.' },
  { flow: 'wellness', stepId: 'breastfeeding', sortOrder: 18, titleAr: 'رضاعة طبيعية؟', reasonAr: 'سعرات وتعافي وترطيب.' },
  { flow: 'wellness', stepId: 'femaleHealthConditions', sortOrder: 19, titleAr: 'حالات صحية', reasonAr: 'PCOS / thyroid / anemia — سياق فقط.' },
  { flow: 'wellness', stepId: 'birthControl', sortOrder: 20, titleAr: 'منع حمل هرموني', reasonAr: 'Level 2 — اختياري.' },
  { flow: 'wellness', stepId: 'menopause', sortOrder: 21, titleAr: 'سن اليأس', reasonAr: 'Level 2 — للعمر 40+.' },
  { flow: 'wellness', stepId: 'cycleLength', sortOrder: 22, titleAr: 'طول الدورة', reasonAr: 'Level 2 — اختياري.' },
];

async function seedOnboardingQuestionCatalog(prisma) {
  for (const row of ONBOARDING_QUESTION_CATALOG) {
    await prisma.onboardingQuestionCatalog.upsert({
      where: { flow_stepId: { flow: row.flow, stepId: row.stepId } },
      create: {
        flow: row.flow,
        stepId: row.stepId,
        sortOrder: row.sortOrder,
        titleAr: row.titleAr,
        reasonAr: row.reasonAr ?? null,
        stepType: row.stepType ?? null,
        options: row.options ?? null,
      },
      update: {
        sortOrder: row.sortOrder,
        titleAr: row.titleAr,
        reasonAr: row.reasonAr ?? null,
        stepType: row.stepType ?? null,
        options: row.options ?? null,
      },
    });
  }
  console.log(`[seed] onboarding_question_catalog: ${ONBOARDING_QUESTION_CATALOG.length} rows`);
}

module.exports = { seedOnboardingQuestionCatalog, ONBOARDING_QUESTION_CATALOG };
