/**
 * Build a user-friendly PDF report from gathered account export data.
 */
const fs = require('fs');
const path = require('path');
const PDFDocument = require('pdfkit');
const sharp = require('sharp');

const FONT_AR = path.join(__dirname, '../../assets/fonts/NotoSansArabic-Regular.ttf');
const LOGO_PATH = path.join(__dirname, '../../assets/logo.png');
const COVER_BANNER_H = 140;
const BRAND = '#4f46e5';
const MUTED = '#64748b';
const BORDER = '#e2e8f0';

const COPY = {
  en: {
    title: 'Taqwin Account Data Export',
    subtitle: 'Your personal data summary',
    exportedAt: 'Exported on',
    account: 'Account',
    profile: 'Profile',
    summary: 'Summary',
    workouts: 'Workout history',
    nutrition: 'Nutrition log',
    orders: 'Orders',
    gamification: 'Progress & achievements',
    notifications: 'Recent notifications',
    community: 'Community activity',
    support: 'Support tickets',
    footer: 'Generated by Taqwin · For your personal records only',
    email: 'Email',
    role: 'Role',
    phone: 'Phone',
    memberSince: 'Member since',
    twoFactor: 'Two-factor authentication',
    telegram: 'Telegram alerts',
    displayName: 'Display name',
    language: 'Language',
    timezone: 'Timezone',
    theme: 'Theme',
    yes: 'Yes',
    no: 'No',
    enabled: 'Enabled',
    disabled: 'Disabled',
    linked: 'Linked',
    notLinked: 'Not linked',
    none: '—',
    noRecords: 'No records in this section.',
    showingLatest: (n, total) => `Showing latest ${n} of ${total}`,
    date: 'Date',
    workout: 'Workout',
    duration: 'Duration',
    food: 'Food',
    grams: 'Grams',
    calories: 'Calories',
    status: 'Status',
    total: 'Total',
    items: 'Items',
    type: 'Type',
    colTitle: 'Title',
    message: 'Message',
    subject: 'Subject',
    tier: 'Tier',
    lifetimeXp: 'Lifetime XP',
    currentXp: 'Current XP',
    achievement: 'Achievement',
    earned: 'Earned',
    posts: 'Posts',
    comments: 'Comments',
    connections: 'Follow connections',
    notificationsCount: 'Notifications',
    min: 'min',
  },
  ar: {
    title: 'تصدير بيانات حساب تكوين',
    subtitle: 'ملخص بياناتك الشخصية',
    exportedAt: 'تاريخ التصدير',
    account: 'الحساب',
    profile: 'الملف الشخصي',
    summary: 'ملخص',
    workouts: 'سجل التمارين',
    nutrition: 'سجل التغذية',
    orders: 'الطلبات',
    gamification: 'التقدّم والإنجازات',
    notifications: 'التنبيهات الأخيرة',
    community: 'نشاط المجتمع',
    support: 'تذاكر الدعم',
    footer: 'أُنشئ بواسطة تكوين · لاستخدامك الشخصي فقط',
    email: 'البريد الإلكتروني',
    role: 'الدور',
    phone: 'الهاتف',
    memberSince: 'عضو منذ',
    twoFactor: 'المصادقة الثنائية',
    telegram: 'تنبيهات Telegram',
    displayName: 'اسم العرض',
    language: 'اللغة',
    timezone: 'المنطقة الزمنية',
    theme: 'المظهر',
    yes: 'نعم',
    no: 'لا',
    enabled: 'مفعّل',
    disabled: 'معطّل',
    linked: 'مربوط',
    notLinked: 'غير مربوط',
    none: '—',
    noRecords: 'لا توجد سجلات في هذا القسم.',
    showingLatest: (n, total) => `آخر ${n} من ${total}`,
    date: 'التاريخ',
    workout: 'التمرين',
    duration: 'المدة',
    food: 'الطعام',
    grams: 'الجرام',
    calories: 'السعرات',
    status: 'الحالة',
    total: 'الإجمالي',
    items: 'العناصر',
    type: 'النوع',
    colTitle: 'العنوان',
    message: 'الرسالة',
    subject: 'الموضوع',
    tier: 'المستوى',
    lifetimeXp: 'XP الإجمالي',
    currentXp: 'XP الحالي',
    achievement: 'الإنجاز',
    earned: 'تاريخ الحصول',
    posts: 'المنشورات',
    comments: 'التعليقات',
    connections: 'المتابعات',
    notificationsCount: 'التنبيهات',
    min: 'د',
  },
};

function resolveLang(settings) {
  return settings?.language === 'ar' ? 'ar' : 'en';
}

function fmtDate(value, lang) {
  if (!value) return '—';
  const d = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(d.getTime())) return '—';
  return d.toLocaleDateString(lang === 'ar' ? 'ar-EG' : 'en-GB', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });
}

function fmtDateTime(value, lang) {
  if (!value) return '—';
  const d = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(d.getTime())) return '—';
  return d.toLocaleString(lang === 'ar' ? 'ar-EG' : 'en-GB', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

function clip(text, max = 120) {
  const s = String(text || '').replace(/\s+/g, ' ').trim();
  if (s.length <= max) return s || '—';
  return `${s.slice(0, max - 1)}…`;
}

function boolLabel(value, labels) {
  return value ? labels.yes : labels.no;
}

function displayProfileName(profile) {
  if (!profile) return null;
  return profile.displayName || profile.businessName || null;
}

function orderItemsSummary(order, lang) {
  const items = order.items || [];
  if (!items.length) return '—';
  return items
    .map((item) => {
      const name =
        lang === 'ar' && item.product?.nameAr ? item.product.nameAr : item.product?.name || 'Item';
      return `${name} ×${item.quantity}`;
    })
    .join(', ');
}

let coverBlurCache = null;

async function getCoverBlurImage(width, height) {
  if (!fs.existsSync(LOGO_PATH)) return null;
  const key = `${Math.round(width)}x${Math.round(height)}`;
  if (coverBlurCache?.key === key) return coverBlurCache.buffer;
  try {
    const buffer = await sharp(LOGO_PATH)
      .resize(Math.ceil(width), Math.ceil(height), { fit: 'cover', position: 'centre' })
      .blur(22)
      .modulate({ brightness: 1.08, saturation: 1.15 })
      .png()
      .toBuffer();
    coverBlurCache = { key, buffer };
    return buffer;
  } catch {
    return null;
  }
}

class PdfWriter {
  constructor(doc, labels, lang) {
    this.doc = doc;
    this.labels = labels;
    this.lang = lang;
    this.isAr = lang === 'ar';
    this.margin = 48;
    this.pageWidth = doc.page.width;
    this.contentWidth = this.pageWidth - this.margin * 2;
    this.fontBody = this.isAr && fs.existsSync(FONT_AR) ? 'NotoArabic' : 'Helvetica';
    this.fontBold = this.isAr && fs.existsSync(FONT_AR) ? 'NotoArabic' : 'Helvetica-Bold';
    this.y = this.margin;
  }

  textX(align = 'start') {
    if (!this.isAr) return this.margin;
    if (align === 'end') return this.pageWidth - this.margin;
    return this.margin;
  }

  ensureSpace(height) {
    if (this.y + height <= this.doc.page.height - this.margin) return;
    this.doc.addPage();
    this.y = this.margin;
  }

  drawCover(payload, blurBg) {
    const { user } = payload;
    const bannerH = COVER_BANNER_H;

    if (blurBg) {
      this.doc.image(blurBg, 0, 0, { width: this.pageWidth, height: bannerH });
    } else {
      this.doc.rect(0, 0, this.pageWidth, bannerH).fill('#f1f5f9');
    }

    this.doc.save();
    this.doc.opacity(0.42);
    this.doc.rect(0, 0, this.pageWidth, bannerH).fill('#ffffff');
    this.doc.restore();

    const logoSize = 88;
    const logoPad = 8;
    if (fs.existsSync(LOGO_PATH)) {
      const logoX = this.isAr ? this.margin + logoPad : this.pageWidth - this.margin - logoSize - logoPad;
      const logoY = (bannerH - logoSize) / 2;
      this.doc.image(LOGO_PATH, logoX, logoY, { fit: [logoSize, logoSize] });
    }

    const textWidth = this.contentWidth - logoSize - 24;
    this.doc.fillColor('#0f172a').font(this.fontBold).fontSize(24);
    this.doc.text(this.labels.title, this.margin, 44, {
      width: textWidth,
      align: this.isAr ? 'right' : 'left',
    });
    this.doc.font(this.fontBody).fontSize(11).fillColor('#475569');
    this.doc.text(this.labels.subtitle, this.margin, 80, {
      width: textWidth,
      align: this.isAr ? 'right' : 'left',
    });
    this.y = 168;
    this.doc.fillColor('#0f172a').font(this.fontBody).fontSize(11);
    const lines = [
      [this.labels.email, user?.email || '—'],
      [this.labels.exportedAt, fmtDateTime(payload.exportedAt, this.lang)],
    ];
    for (const [k, v] of lines) {
      this.drawKeyValue(k, v);
    }
    this.y += 8;
  }

  sectionTitle(title) {
    this.ensureSpace(36);
    this.doc.fillColor(BRAND).font(this.fontBold).fontSize(14);
    this.doc.text(title, this.textX(), this.y, {
      width: this.contentWidth,
      align: this.isAr ? 'right' : 'left',
    });
    this.y += 22;
    this.doc
      .strokeColor(BORDER)
      .lineWidth(1)
      .moveTo(this.margin, this.y)
      .lineTo(this.pageWidth - this.margin, this.y)
      .stroke();
    this.y += 14;
  }

  drawKeyValue(key, value) {
    this.ensureSpace(20);
    this.doc.fillColor(MUTED).font(this.fontBody).fontSize(9);
    this.doc.text(key, this.margin, this.y, {
      width: 160,
      align: this.isAr ? 'right' : 'left',
    });
    this.doc.fillColor('#0f172a').font(this.fontBody).fontSize(10);
    this.doc.text(String(value ?? '—'), this.margin + (this.isAr ? 0 : 170), this.y, {
      width: this.contentWidth - 170,
      align: this.isAr ? 'right' : 'left',
    });
    this.y += 18;
  }

  drawStatsGrid(stats) {
    const cols = 2;
    const colW = this.contentWidth / cols;
    const rowH = 52;
    this.ensureSpace(rowH * Math.ceil(stats.length / cols) + 8);
    stats.forEach((stat, i) => {
      const col = i % cols;
      const row = Math.floor(i / cols);
      const x = this.margin + col * colW;
      const y = this.y + row * rowH;
      this.doc.roundedRect(x, y, colW - 10, rowH - 8, 6).fillAndStroke('#f8fafc', BORDER);
      this.doc.fillColor(MUTED).font(this.fontBody).fontSize(8);
      this.doc.text(stat.label, x + 10, y + 10, { width: colW - 24, align: this.isAr ? 'right' : 'left' });
      this.doc.fillColor('#0f172a').font(this.fontBold).fontSize(16);
      this.doc.text(String(stat.value), x + 10, y + 26, { width: colW - 24, align: this.isAr ? 'right' : 'left' });
    });
    this.y += rowH * Math.ceil(stats.length / cols) + 6;
  }

  drawTable(headers, rows, colWidths) {
    if (!rows.length) {
      this.ensureSpace(20);
      this.doc.fillColor(MUTED).font(this.fontBody).fontSize(10);
      this.doc.text(this.labels.noRecords, this.margin, this.y, {
        width: this.contentWidth,
        align: this.isAr ? 'right' : 'left',
      });
      this.y += 24;
      return;
    }

    const rowH = 22;
    const headerH = 24;
    this.ensureSpace(headerH + 8);

    let x = this.margin;
    this.doc.rect(this.margin, this.y, this.contentWidth, headerH).fill('#f1f5f9');
    headers.forEach((header, i) => {
      this.doc.fillColor('#334155').font(this.fontBold).fontSize(8);
      this.doc.text(header, x + 4, this.y + 7, {
        width: colWidths[i] - 8,
        align: this.isAr ? 'right' : 'left',
      });
      x += colWidths[i];
    });
    this.y += headerH;

    for (const row of rows) {
      this.ensureSpace(rowH);
      let cx = this.margin;
      this.doc.strokeColor(BORDER).lineWidth(0.5);
      this.doc
        .moveTo(this.margin, this.y + rowH)
        .lineTo(this.pageWidth - this.margin, this.y + rowH)
        .stroke();
      row.forEach((cell, i) => {
        this.doc.fillColor('#0f172a').font(this.fontBody).fontSize(8);
        this.doc.text(String(cell ?? '—'), cx + 4, this.y + 6, {
          width: colWidths[i] - 8,
          align: this.isAr ? 'right' : 'left',
          ellipsis: true,
        });
        cx += colWidths[i];
      });
      this.y += rowH;
    }
    this.y += 10;
  }

  drawBulletList(items) {
    if (!items.length) {
      this.ensureSpace(20);
      this.doc.fillColor(MUTED).font(this.fontBody).fontSize(10);
      this.doc.text(this.labels.noRecords, this.margin, this.y, {
        width: this.contentWidth,
        align: this.isAr ? 'right' : 'left',
      });
      this.y += 24;
      return;
    }
    for (const item of items) {
      this.ensureSpace(18);
      this.doc.fillColor('#0f172a').font(this.fontBody).fontSize(9);
      this.doc.text(`• ${item}`, this.margin + (this.isAr ? 0 : 6), this.y, {
        width: this.contentWidth - 6,
        align: this.isAr ? 'right' : 'left',
      });
      this.y += 16;
    }
    this.y += 4;
  }

  addFooters() {
    const pages = this.doc.bufferedPageRange();
    for (let i = 0; i < pages.count; i += 1) {
      this.doc.switchToPage(i);
      this.doc.fillColor(MUTED).font(this.fontBody).fontSize(8);
      this.doc.text(this.labels.footer, this.margin, this.doc.page.height - 32, {
        width: this.contentWidth,
        align: 'center',
      });
      this.doc.text(`${i + 1} / ${pages.count}`, this.margin, this.doc.page.height - 32, {
        width: this.contentWidth,
        align: this.isAr ? 'left' : 'right',
      });
    }
  }
}

function renderSections(writer, payload) {
  const { labels, lang } = writer;
  const { user, profile, settings } = payload;

  writer.sectionTitle(labels.account);
  writer.drawKeyValue(labels.email, user?.email);
  writer.drawKeyValue(labels.role, user?.role);
  if (user?.phone) writer.drawKeyValue(labels.phone, user.phone);
  writer.drawKeyValue(labels.memberSince, fmtDate(user?.createdAt, lang));
  writer.drawKeyValue(labels.twoFactor, boolLabel(user?.twoFactorEnabled, labels));
  writer.drawKeyValue(
    labels.telegram,
    user?.telegramLinkedAt ? labels.linked : labels.notLinked,
  );

  writer.sectionTitle(labels.profile);
  const name = displayProfileName(profile);
  if (name) writer.drawKeyValue(labels.displayName, name);
  if (settings) {
    writer.drawKeyValue(labels.language, settings.language || '—');
    writer.drawKeyValue(labels.timezone, settings.timezone || '—');
    writer.drawKeyValue(labels.theme, settings.theme || '—');
  } else {
    writer.doc.fillColor(MUTED).font(writer.fontBody).fontSize(10);
    writer.doc.text(labels.noRecords, writer.margin, writer.y);
    writer.y += 20;
  }

  writer.sectionTitle(labels.summary);
  writer.drawStatsGrid([
    { label: labels.workouts, value: payload.workoutLogs.length },
    { label: labels.nutrition, value: payload.foodLogs.length },
    { label: labels.orders, value: payload.orders.length },
    { label: labels.posts, value: payload.communityPosts.length },
    { label: labels.comments, value: payload.communityComments.length },
    { label: labels.notificationsCount, value: payload.notifications.length },
  ]);

  writer.sectionTitle(labels.workouts);
  if (payload.workoutLogs.length > 50) {
    writer.doc.fillColor(MUTED).font(writer.fontBody).fontSize(8);
    writer.doc.text(labels.showingLatest(50, payload.workoutLogs.length), writer.margin, writer.y, {
      width: writer.contentWidth,
      align: writer.isAr ? 'right' : 'left',
    });
    writer.y += 14;
  }
  writer.drawTable(
    [labels.date, labels.workout, labels.duration],
    payload.workoutLogs.slice(0, 50).map((log) => [
      fmtDate(log.loggedAt, lang),
      clip(log.workout?.title || '—', 40),
      log.durationMin != null ? `${log.durationMin} ${labels.min}` : '—',
    ]),
    [90, writer.contentWidth - 170, 80],
  );

  writer.sectionTitle(labels.nutrition);
  if (payload.foodLogs.length > 50) {
    writer.doc.fillColor(MUTED).font(writer.fontBody).fontSize(8);
    writer.doc.text(labels.showingLatest(50, payload.foodLogs.length), writer.margin, writer.y, {
      width: writer.contentWidth,
      align: writer.isAr ? 'right' : 'left',
    });
    writer.y += 14;
  }
  writer.drawTable(
    [labels.date, labels.food, labels.grams, labels.calories],
    payload.foodLogs.slice(0, 50).map((log) => [
      fmtDate(log.loggedAt, lang),
      clip(log.snapshotName || '—', 36),
      log.grams != null ? Math.round(log.grams) : '—',
      log.snapshotCalories != null ? Math.round(log.snapshotCalories) : '—',
    ]),
    [80, writer.contentWidth - 210, 55, 75],
  );

  writer.sectionTitle(labels.orders);
  writer.drawTable(
    [labels.date, labels.status, labels.total, labels.items],
    payload.orders.slice(0, 30).map((order) => [
      fmtDate(order.createdAt, lang),
      order.status,
      `${order.total} ${order.currency || ''}`.trim(),
      clip(orderItemsSummary(order, lang), 50),
    ]),
    [80, 80, 90, writer.contentWidth - 250],
  );

  writer.sectionTitle(labels.gamification);
  if (payload.gamification) {
    writer.drawKeyValue(labels.tier, payload.gamification.currentTier);
    writer.drawKeyValue(labels.lifetimeXp, payload.gamification.lifetimeXp);
    writer.drawKeyValue(labels.currentXp, payload.gamification.currentXp);
  }
  if (payload.achievements.length) {
    writer.drawTable(
      [labels.achievement, labels.earned],
      payload.achievements.slice(0, 40).map((a) => [a.slug, fmtDate(a.earnedAt, lang)]),
      [writer.contentWidth - 120, 120],
    );
  } else if (!payload.gamification) {
    writer.drawBulletList([]);
  }

  writer.sectionTitle(labels.notifications);
  writer.drawTable(
    [labels.date, labels.type, labels.colTitle],
    payload.notifications.slice(0, 25).map((n) => [
      fmtDate(n.createdAt, lang),
      clip(n.type, 28),
      clip(n.title, 42),
    ]),
    [80, 130, writer.contentWidth - 210],
  );

  writer.sectionTitle(labels.community);
  writer.drawKeyValue(labels.posts, payload.communityPosts.length);
  writer.drawKeyValue(labels.comments, payload.communityComments.length);
  writer.drawKeyValue(labels.connections, payload.communityFollows.length);
  if (payload.communityPosts.length) {
    writer.drawBulletList(
      payload.communityPosts.slice(0, 8).map((p) => `${fmtDate(p.createdAt, lang)} — ${clip(p.content, 80)}`),
    );
  }

  writer.sectionTitle(labels.support);
  writer.drawTable(
    [labels.date, labels.subject, labels.status],
    payload.supportTickets.slice(0, 20).map((t) => [
      fmtDate(t.createdAt, lang),
      clip(t.subject, 50),
      t.status,
    ]),
    [80, writer.contentWidth - 160, 80],
  );
}

async function buildAccountExportPdf(payload) {
  const lang = resolveLang(payload.settings);
  const labels = COPY[lang];

  const doc = new PDFDocument({ margin: 48, size: 'A4', bufferPages: true });
  const chunks = [];
  const done = new Promise((resolve, reject) => {
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
  });

  if (lang === 'ar' && fs.existsSync(FONT_AR)) {
    doc.registerFont('NotoArabic', FONT_AR);
  }

  const blurBg = await getCoverBlurImage(doc.page.width, COVER_BANNER_H);
  const writer = new PdfWriter(doc, labels, lang);
  writer.drawCover(payload, blurBg);
  renderSections(writer, payload);
  writer.addFooters();
  doc.end();
  return done;
}

module.exports = { buildAccountExportPdf, resolveLang };
