import type { OnboardingStep } from './types';
import { ASSETS } from './onboardingAssets';

export const ATHLETE_ONBOARDING_STEPS: OnboardingStep[] = [
  // ─── PRE ───────────────────────────────────────────────────────────────────
  {
    id: 'programIntro',
    section: 'pre',
    type: 'hero',
    title: 'Strength program',
    subtitle: 'Built for you on Taqwin',
    body: 'We tailor volume, recovery, and coaching to your age, goals, and lifestyle — the same flow trusted by structured training apps.',
    cta: 'Get started',
    heroImage: ASSETS.heroStrength,
  },
  {
    id: 'ageRange',
    section: 'pre',
    type: 'single',
    title: 'Based on your age',
    subtitle: 'We adapt intensity and recovery to your life stage.',
    autoAdvance: true,
    options: [
      { value: '18-29', label: 'Age: 18–29', imageUrl: ASSETS.age1829 },
      { value: '30-39', label: 'Age: 30–39', imageUrl: ASSETS.age3039 },
      { value: '40-49', label: 'Age: 40–49', imageUrl: ASSETS.age4049 },
      { value: '50+', label: 'Age: 50+', imageUrl: ASSETS.age50plus },
    ],
  },
  {
    id: 'gender',
    section: 'pre',
    type: 'single',
    title: 'Select your gender',
    subtitle: 'This helps us personalize your plan.',
    autoAdvance: true,
    options: [
      { value: 'Male', label: 'Male', imageUrl: ASSETS.genderMale },
      { value: 'Female', label: 'Female', imageUrl: ASSETS.genderFemale },
    ],
  },

  // ─── GOALS ─────────────────────────────────────────────────────────────────
  {
    id: 'primaryGoal',
    section: 'goals',
    type: 'single',
    title: 'What is your primary goal today?',
    autoAdvance: true,
    options: [
      { value: 'Build Muscle', label: 'More muscle & full-body strength', imageUrl: ASSETS.goalMuscle },
      { value: 'Lose Weight', label: 'Weight loss & leaner physique', imageUrl: ASSETS.goalWeight },
      { value: 'Improve Endurance', label: 'Endurance & conditioning', imageUrl: ASSETS.goalEndurance },
      { value: 'Stay Healthy', label: 'Mental balance & wellbeing', imageUrl: ASSETS.goalWellness },
    ],
  },
  {
    id: 'goalProof',
    section: 'goals',
    type: 'info',
    title: 'Up to 35% stronger in the first 3 months',
    body: 'Members who follow a structured plan see measurable strength gains within 12 weeks.',
    cta: 'Build my strength plan',
  },
  {
    id: 'goalLikert',
    section: 'goals',
    type: 'likert',
    title: 'How true is this for you?',
    statement: 'I want a training plan that adapts as I get stronger.',
  },
  {
    id: 'physique',
    section: 'goals',
    type: 'single',
    title: 'What type of physique are you aiming for?',
    autoAdvance: true,
    options: [
      { value: 'Lean', label: 'Lean', description: 'Defined, athletic look', imageUrl: ASSETS.physiqueLean },
      { value: 'Muscular', label: 'Muscular', description: 'Prominent musculature', imageUrl: ASSETS.physiqueMuscular },
      { value: 'Ripped', label: 'Ripped', description: 'Very low body fat', imageUrl: ASSETS.physiqueRipped },
    ],
  },
  {
    id: 'successMetrics',
    section: 'goals',
    type: 'multi',
    title: 'Which best measures fitness success for you?',
    subtitle: 'Choose up to 3',
    maxSelect: 3,
    options: [
      { value: 'muscle_gain', label: 'Muscle gain', description: 'Building muscle and size' },
      { value: 'strength', label: 'Increased strength', description: 'Lifting more weight' },
      { value: 'endurance', label: 'Improved endurance', description: 'Better cardio capacity' },
      { value: 'weight_loss', label: 'Weight loss', description: 'Lower scale numbers' },
      { value: 'measurements', label: 'Body measurements', description: 'Size and shape changes' },
      { value: 'wellbeing', label: 'Overall fitness', description: 'Energy and wellbeing' },
    ],
  },
  {
    id: 'bodyFocus',
    section: 'goals',
    type: 'multi',
    title: 'Which areas would you like to focus on?',
    options: [
      { value: 'full_body', label: 'Full body' },
      { value: 'shoulders', label: 'Shoulders' },
      { value: 'biceps', label: 'Arms / biceps' },
      { value: 'back', label: 'Back' },
      { value: 'chest', label: 'Chest' },
      { value: 'core', label: 'Core / six-pack' },
      { value: 'glutes', label: 'Glutes' },
      { value: 'legs', label: 'Legs' },
    ],
  },
  {
    id: 'trackProgress',
    section: 'goals',
    type: 'multi',
    title: 'How do you prefer to track strength improvement?',
    options: [
      { value: 'heavier_weights', label: 'Heavier weights', description: 'Increasing load in workouts' },
      { value: 'milestones', label: 'New milestones', description: 'Personal records' },
      { value: 'reps', label: 'More repetitions', description: 'Higher rep quality' },
      { value: 'compounds', label: 'Compound lifts', description: 'Squat, deadlift, press' },
    ],
  },
  {
    id: 'feelings',
    section: 'goals',
    type: 'multi',
    title: 'How do you hope to feel on your fitness journey?',
    options: [
      { value: 'energized', label: 'Energized', description: 'More vitality' },
      { value: 'confident', label: 'Confident', description: 'Empowered and in control' },
      { value: 'relaxed', label: 'Relaxed', description: 'Less stress in your body' },
      { value: 'accomplished', label: 'Accomplished', description: 'Sense of progress' },
    ],
  },

  // ─── WORKOUT ───────────────────────────────────────────────────────────────
  {
    id: 'workoutLocation',
    section: 'workout',
    type: 'single',
    title: 'Where do you prefer to work out?',
    autoAdvance: true,
    options: [
      { value: 'Home', label: 'Home', imageUrl: ASSETS.workoutHome },
      { value: 'Gym', label: 'Gym', imageUrl: ASSETS.workoutGym },
      { value: 'Mixed', label: 'Mixed', imageUrl: ASSETS.workoutMixed },
    ],
  },
  {
    id: 'gymType',
    section: 'workout',
    type: 'single',
    title: 'Which type of gym do you exercise at?',
    autoAdvance: true,
    options: [
      { value: 'large', label: 'Large gym' },
      { value: 'small', label: 'Small gym' },
      { value: 'garage', label: 'Garage gym' },
      { value: 'home', label: 'Home gym' },
    ],
  },
  {
    id: 'addCardio',
    section: 'workout',
    type: 'single',
    title: 'Should we add cardio to your plan?',
    autoAdvance: true,
    options: [
      { value: 'yes', label: 'Yes' },
      { value: 'no', label: 'Not now' },
    ],
  },
  {
    id: 'equipment',
    section: 'workout',
    type: 'multi',
    title: 'What equipment do you have access to?',
    options: [
      { value: 'treadmill', label: 'Treadmill' },
      { value: 'bike', label: 'Stationary bike' },
      { value: 'assault_bike', label: 'Assault bike' },
      { value: 'elliptical', label: 'Elliptical' },
      { value: 'stepper', label: 'Stepper' },
      { value: 'rower', label: 'Rower' },
    ],
  },
  {
    id: 'workoutTime',
    section: 'workout',
    type: 'single',
    title: 'When do you prefer to work out?',
    autoAdvance: true,
    options: [
      { value: 'morning', label: 'Morning' },
      { value: 'afternoon', label: 'Afternoon' },
      { value: 'evening', label: 'Evening' },
      { value: 'varies', label: 'At different times' },
    ],
  },
  {
    id: 'workoutDuration',
    section: 'workout',
    type: 'single',
    title: 'How much time can you dedicate per workout?',
    autoAdvance: true,
    options: [
      { value: '30', label: 'About 30 minutes' },
      { value: '45', label: 'About 45 minutes' },
      { value: '60', label: 'One hour or so' },
      { value: '90', label: 'More than an hour' },
    ],
  },
  {
    id: 'otherSports',
    section: 'workout',
    type: 'multi',
    title: 'Other sports to consider in your plan?',
    options: [
      { value: 'cardio', label: 'Cardio', description: 'Running, rowing, cycling' },
      { value: 'flexibility', label: 'Flexibility', description: 'Yoga, stretching' },
      { value: 'martial', label: 'Martial arts' },
      { value: 'team', label: 'Team sports' },
      { value: 'none', label: 'No' },
    ],
  },

  // ─── PERSONAL ──────────────────────────────────────────────────────────────
  {
    id: 'bodyType',
    section: 'personal',
    type: 'single',
    title: 'Determine your body type',
    autoAdvance: true,
    options: [
      { value: 'ectomorph', label: 'Ectomorph', description: 'Lean build, hard to gain mass', imageUrl: ASSETS.bodyEctomorph },
      { value: 'mesomorph', label: 'Mesomorph', description: 'Athletic, muscular build', imageUrl: ASSETS.bodyMesomorph },
      { value: 'endomorph', label: 'Endomorph', description: 'Stores fat easily', imageUrl: ASSETS.bodyEndomorph },
    ],
  },
  {
    id: 'bodyFat',
    section: 'personal',
    type: 'slider',
    title: 'Choose your level of body fat',
    field: 'bodyFat',
    levels: [
      { value: '5-9', label: '5–9%' },
      { value: '10-14', label: '10–14%' },
      { value: '15-19', label: '15–19%' },
      { value: '20-24', label: '20–24%' },
      { value: '25-29', label: '25–29%' },
      { value: '30-34', label: '30–34%' },
      { value: '35+', label: '35%+' },
    ],
  },
  {
    id: 'height',
    section: 'personal',
    type: 'number',
    title: 'How tall are you?',
    field: 'height',
    unit: 'cm',
    placeholder: '175',
    min: 100,
    max: 250,
    requireConsent: true,
  },
  {
    id: 'weight',
    section: 'personal',
    type: 'number',
    title: 'What is your current weight?',
    field: 'weight',
    unit: 'kg',
    placeholder: '75',
    min: 30,
    max: 300,
  },
  {
    id: 'targetWeight',
    section: 'personal',
    type: 'number',
    title: 'What is your target weight?',
    field: 'targetWeight',
    unit: 'kg',
    placeholder: '80',
    min: 30,
    max: 300,
  },
  {
    id: 'age',
    section: 'personal',
    type: 'number',
    title: 'How old are you?',
    field: 'age',
    placeholder: '25',
    min: 13,
    max: 100,
  },

  // ─── FITNESS ───────────────────────────────────────────────────────────────
  {
    id: 'fitnessLevel',
    section: 'fitness',
    type: 'single',
    title: 'What is your fitness level?',
    autoAdvance: true,
    options: [
      { value: 'Beginner', label: 'Beginner', description: 'New or returning after a break', imageUrl: ASSETS.levelBeginner },
      { value: 'Intermediate', label: 'Intermediate', description: 'Regular training experience', imageUrl: ASSETS.levelIntermediate },
      { value: 'Advanced', label: 'Advanced', description: 'Years of consistent training', imageUrl: ASSETS.levelAdvanced },
    ],
  },
  {
    id: 'pastTraining',
    section: 'fitness',
    type: 'multi',
    title: 'Have you trained with any of these before?',
    options: [
      { value: 'trainer', label: 'Personal trainers' },
      { value: 'apps', label: 'Fitness apps' },
      { value: 'videos', label: 'Workout videos' },
      { value: 'self', label: 'Self-taught' },
      { value: 'none', label: 'None' },
    ],
  },
  {
    id: 'injuries',
    section: 'fitness',
    type: 'multi',
    title: 'Are any parts of your body injured?',
    options: [
      { value: 'none', label: 'None' },
      { value: 'back', label: 'Back' },
      { value: 'knees', label: 'Knees' },
      { value: 'shoulders', label: 'Shoulders' },
      { value: 'neck', label: 'Neck' },
      { value: 'arms', label: 'Arms' },
      { value: 'elbows', label: 'Elbows' },
      { value: 'legs', label: 'Legs' },
    ],
  },
  {
    id: 'pastActivities',
    section: 'fitness',
    type: 'multi',
    title: 'Have you tried any of these to improve your physique?',
    options: [
      { value: 'nutrition', label: 'Nutrition changes' },
      { value: 'weights', label: 'Weight training' },
      { value: 'cardio', label: 'Cardio' },
      { value: 'bodyweight', label: 'Bodyweight training' },
      { value: 'sports', label: 'Team sports' },
    ],
  },
  {
    id: 'pushups',
    section: 'fitness',
    type: 'single',
    title: 'How many push-ups can you do?',
    autoAdvance: true,
    options: [
      { value: 'lt12', label: 'Fewer than 12' },
      { value: '13-20', label: '13–20' },
      { value: 'gt20', label: 'More than 20' },
      { value: 'unknown', label: "I don't know" },
    ],
  },
  {
    id: 'squats',
    section: 'fitness',
    type: 'single',
    title: 'How many squats can you do?',
    autoAdvance: true,
    options: [
      { value: 'lt12', label: 'Fewer than 12' },
      { value: '13-20', label: '13–20' },
      { value: 'gt20', label: 'More than 20' },
      { value: 'unknown', label: "I don't know" },
    ],
  },
  {
    id: 'deadliftMax',
    section: 'fitness',
    type: 'weightOptional',
    title: "What's the heaviest weight you can deadlift?",
    field: 'deadliftMax',
  },
  {
    id: 'benchMax',
    section: 'fitness',
    type: 'weightOptional',
    title: "What's the heaviest weight you can bench press?",
    field: 'benchMax',
  },
  {
    id: 'fitnessSummary',
    section: 'fitness',
    type: 'summary',
    title: 'Your fitness level',
  },

  // ─── LIFESTYLE ─────────────────────────────────────────────────────────────
  {
    id: 'exerciseAttitude',
    section: 'lifestyle',
    type: 'single',
    title: 'What does exercise mean in your life?',
    autoAdvance: true,
    options: [
      { value: 'necessary', label: 'Necessary', description: 'Part of my routine' },
      { value: 'inconvenient', label: 'Inconvenient', description: 'Hard to fit in' },
      { value: 'enjoyable', label: 'Enjoyable', description: 'Something I look forward to' },
    ],
  },
  {
    id: 'eatingHabits',
    section: 'lifestyle',
    type: 'single',
    title: 'How would you describe your eating habits?',
    autoAdvance: true,
    options: [
      { value: 'emotional', label: 'Emotional eater' },
      { value: 'bored', label: 'Boredom eater' },
      { value: 'unconscious', label: 'Unconscious eater' },
      { value: 'habitual', label: 'Habitual eater' },
      { value: 'energy', label: 'Energy eater' },
    ],
  },
  {
    id: 'stressCoping',
    section: 'lifestyle',
    type: 'multi',
    title: 'How do you cope with stress?',
    options: [
      { value: 'exercise', label: 'Exercising' },
      { value: 'creative', label: 'Being creative' },
      { value: 'outdoors', label: 'Getting outdoors' },
      { value: 'eating', label: 'Eating more or less' },
    ],
  },
  {
    id: 'sleep',
    section: 'lifestyle',
    type: 'single',
    title: 'How much sleep do you get per night?',
    autoAdvance: true,
    options: [
      { value: 'lt5', label: 'Fewer than 5 hours' },
      { value: '5-6', label: '5–6 hours' },
      { value: '7-8', label: '7–8 hours' },
      { value: 'gt8', label: 'Over 8 hours' },
    ],
  },
  {
    id: 'walking',
    section: 'lifestyle',
    type: 'single',
    title: 'How much do you walk daily?',
    autoAdvance: true,
    options: [
      { value: 'lt1', label: 'Less than 1 hour' },
      { value: '1-2', label: '1–2 hours' },
      { value: 'gt2', label: 'More than 2 hours' },
    ],
  },
  {
    id: 'water',
    section: 'lifestyle',
    type: 'single',
    title: 'How much water do you drink daily?',
    autoAdvance: true,
    options: [
      { value: 'coffee', label: 'Mostly tea / coffee' },
      { value: 'lt2', label: 'Fewer than 2 glasses' },
      { value: '2-6', label: '2–6 glasses' },
      { value: '7-10', label: '7–10 glasses' },
      { value: 'gt10', label: 'More than 10 glasses' },
    ],
  },
  {
    id: 'diet',
    section: 'lifestyle',
    type: 'single',
    title: 'Any dietary preferences or restrictions?',
    autoAdvance: true,
    options: [
      { value: 'none', label: 'None' },
      { value: 'vegetarian', label: 'Vegetarian / vegan' },
      { value: 'gluten', label: 'Gluten-free' },
      { value: 'lactose', label: 'Lactose-free' },
      { value: 'nuts', label: 'Nut allergy' },
    ],
  },
  {
    id: 'tracker',
    section: 'lifestyle',
    type: 'single',
    title: 'Do you use a fitness tracker or smartwatch?',
    autoAdvance: true,
    options: [
      { value: 'yes', label: 'Yes' },
      { value: 'no', label: 'No' },
    ],
  },
  {
    id: 'planFailed',
    section: 'lifestyle',
    type: 'single',
    title: 'Have fitness plans failed to help you before?',
    autoAdvance: true,
    options: [
      { value: 'yes', label: 'Yes' },
      { value: 'no', label: 'No' },
    ],
  },
  {
    id: 'stayOnTrack',
    section: 'lifestyle',
    type: 'info',
    title: 'Taqwin will help you stay on track',
    body: 'Variables like schedule, recovery, and nutrition can block progress. We give you the tools to stay motivated toward your goals.',
    cta: 'Continue',
  },

  // ─── MOTIVATION ────────────────────────────────────────────────────────────
  {
    id: 'motivation',
    section: 'motivation',
    type: 'multi',
    title: 'What made you want to start training?',
    subtitle: 'Select all that apply',
    options: [
      { value: 'visual', label: 'Visual indicators', description: 'Mirror, scale, measurements' },
      { value: 'fitness', label: 'Current fitness levels', description: 'Want to improve' },
      { value: 'health', label: 'Health improvement' },
      { value: 'clothing', label: 'Clothing fit' },
      { value: 'aging', label: 'Aging concerns' },
    ],
  },
  {
    id: 'upcomingEvent',
    section: 'motivation',
    type: 'single',
    title: 'Important event coming up?',
    autoAdvance: true,
    options: [
      { value: 'vacation', label: 'Vacation' },
      { value: 'wedding', label: 'Wedding' },
      { value: 'birthday', label: 'Birthday' },
      { value: 'none', label: 'None of the above' },
    ],
  },
  {
    id: 'supportLikert',
    section: 'motivation',
    type: 'likert',
    title: 'How much do you relate?',
    statement: 'Feeling supported during workouts significantly boosts my motivation.',
  },
  {
    id: 'confidence',
    section: 'motivation',
    type: 'single',
    title: 'Are you confident you will achieve your fitness goals?',
    autoAdvance: true,
    options: [
      { value: 'high', label: 'Highly confident', description: "I'm certain I'll reach my goal" },
      { value: 'reasonable', label: 'Reasonably confident', description: 'Good chance of success' },
      { value: 'optimistic', label: 'Optimistic', description: "I'd like to believe I will" },
      { value: 'low', label: 'Not confident', description: 'I have doubts this time' },
    ],
  },
  {
    id: 'generating',
    section: 'finish',
    type: 'generating',
    title: "We've got you! Tailoring your program…",
  },
  {
    id: 'pace',
    section: 'finish',
    type: 'single',
    title: 'Your action plan is ready!',
    subtitle: 'How quickly do you want to reach your goal?',
    autoAdvance: true,
    options: [
      { value: 'fast', label: 'As quickly as possible' },
      { value: 'steady', label: 'Slow and steady' },
      { value: 'balanced', label: 'Somewhere in between' },
    ],
  },
  {
    id: 'displayName',
    section: 'finish',
    type: 'text',
    title: 'What is your name?',
    field: 'displayName',
    placeholder: 'Preferred first name',
    minLength: 2,
    maxLength: 40,
  },
];

/** Steps skipped based on prior answers */
export function shouldSkipStep(stepId: string, answers: Record<string, unknown>): boolean {
  const loc = answers.workoutLocation as string | undefined;
  if (stepId === 'gymType' && loc !== 'Gym' && loc !== 'Mixed') return true;
  if (stepId === 'equipment' && answers.addCardio !== 'yes') return true;
  return false;
}

export function getActiveSteps(answers: Record<string, unknown>) {
  return ATHLETE_ONBOARDING_STEPS.filter(s => !shouldSkipStep(s.id, answers));
}
