import type { OnboardingStep } from '../types';
import { ASSETS } from '../onboardingAssets';

/** Steps added for multi-flow questionnaires (not in legacy RAW list). */
export const EXTRA_QUESTIONNAIRE_STEPS: OnboardingStep[] = [
  {
    id: 'bodyMeasurements',
    section: 'profile',
    type: 'measurements',
    title: 'Body measurements (optional)',
    subtitle: 'Chest, waist, hips — helps track progress',
    presentation: 'chat',
  },
  {
    id: 'activityLevel',
    section: 'profile',
    type: 'single',
    title: 'Daily activity level',
    subtitle: 'Outside the gym — affects calories and recovery',
    autoAdvance: true,
    options: [
      { value: 'sedentary', label: 'Mostly sitting', description: 'Desk job, little walking' },
      { value: 'light', label: 'Light', description: 'Some walking' },
      { value: 'moderate', label: 'Moderate', description: 'On feet part of the day' },
      { value: 'active', label: 'Active', description: 'Physical job or lots of movement' },
      { value: 'very_active', label: 'Very active', description: 'Highly physical daily life' },
    ],
  },
  {
    id: 'lastTraining',
    section: 'profile',
    type: 'single',
    title: 'Last consistent training',
    autoAdvance: true,
    options: [
      { value: 'never', label: 'Never trained regularly' },
      { value: 'under_3m', label: 'Stopped under 3 months ago' },
      { value: '3_12m', label: '3–12 months ago' },
      { value: 'over_1y', label: 'Over a year ago but experienced' },
      { value: 'current', label: 'Training now' },
    ],
  },
  {
    id: 'inbodyScan',
    section: 'profile',
    type: 'inbody',
    title: 'InBody scan',
    subtitle: 'Optional fields — required to finish this section',
    requireComplete: true,
  },
  {
    id: 'progressPhotos',
    section: 'profile',
    type: 'photos',
    title: 'Progress photos',
    subtitle: 'Front and back — required to finish this section',
    requireComplete: true,
  },
  {
    id: 'goal12Week',
    section: 'training',
    type: 'text',
    title: '12-week training goal',
    field: 'goal12Week',
    placeholder: 'e.g. lose 5 kg fat, add strength on bench…',
    minLength: 3,
    maxLength: 200,
  },
  {
    id: 'trainingDaysPerWeek',
    section: 'training',
    type: 'single',
    title: 'Training days per week',
    autoAdvance: true,
    options: [
      { value: '2', label: '2 days' },
      { value: '3', label: '3 days' },
      { value: '4', label: '4 days' },
      { value: '5', label: '5 days' },
      { value: '6', label: '6 days' },
    ],
  },
  {
    id: 'gymLink',
    section: 'training',
    type: 'text',
    title: 'Link your gym',
    field: 'gymLink',
    placeholder: 'Gym name or ID from Taqwin gyms list',
    minLength: 2,
    maxLength: 120,
  },
  {
    id: 'preferredSplit',
    section: 'training',
    type: 'single',
    title: 'Preferred split / schedule',
    autoAdvance: true,
    options: [
      { value: 'full_body', label: 'Full body' },
      { value: 'upper_lower', label: 'Upper / lower' },
      { value: 'ppl', label: 'Push / pull / legs' },
      { value: 'bro', label: 'Bro split' },
      { value: 'coach', label: 'Let the coach decide' },
    ],
  },
  {
    id: 'exercisesAvoid',
    section: 'training',
    type: 'catalogPicker',
    title: 'Exercises to avoid',
    subtitle: 'Pick from our library — search or browse',
    field: 'exercisesAvoid',
    catalog: 'exercise',
    multi: true,
    maxSelect: 10,
    optional: true,
    searchHints: [
      { label: 'Burpees', query: 'burpee' },
      { label: 'Leg press', query: 'leg press' },
      { label: 'Deadlift', query: 'deadlift' },
    ],
    chatMessage: 'Any moves you want off the plan? Tap the ones to skip — or continue if none.',
  },
  {
    id: 'exercisesLove',
    section: 'training',
    type: 'catalogPicker',
    title: 'Exercises you want included',
    subtitle: 'Your favorites from our library',
    field: 'exercisesLove',
    catalog: 'exercise',
    multi: true,
    maxSelect: 12,
    optional: true,
    searchHints: [
      { label: 'Bench press', query: 'bench press' },
      { label: 'Squat', query: 'squat' },
      { label: 'Rows', query: 'row' },
    ],
    chatMessage: 'Which exercises do you love? Pick a few so we keep them in your program.',
  },
  {
    id: 'pullups',
    section: 'fitness',
    type: 'single',
    title: 'How many pull-ups can you do?',
    autoAdvance: true,
    options: [
      { value: '0', label: 'None yet' },
      { value: 'lt5', label: '1–5' },
      { value: '6_12', label: '6–12' },
      { value: 'gt12', label: 'More than 12' },
      { value: 'unknown', label: "I don't know" },
    ],
  },
  {
    id: 'strengthEquipment',
    section: 'training',
    type: 'multi',
    title: 'Strength equipment available',
    options: [
      { value: 'barbell', label: 'Barbell & rack' },
      { value: 'dumbbells', label: 'Dumbbells' },
      { value: 'cables', label: 'Cable machines' },
      { value: 'machines', label: 'Plate machines' },
      { value: 'kettlebells', label: 'Kettlebells' },
      { value: 'bands', label: 'Resistance bands' },
      { value: 'bodyweight', label: 'Bodyweight only' },
    ],
  },
  {
    id: 'goal12WeekPace',
    section: 'training',
    type: 'single',
    title: '12-week goal intensity',
    autoAdvance: true,
    options: [
      { value: 'fast', label: 'As fast as possible' },
      { value: 'balanced', label: 'Balanced' },
      { value: 'calm', label: 'Slow and steady' },
    ],
  },
  {
    id: 'restDaysPreference',
    section: 'training',
    type: 'single',
    title: 'Rest days',
    autoAdvance: true,
    options: [
      { value: 'fixed', label: 'I want fixed rest days' },
      { value: 'coach', label: 'Coach decides' },
      { value: 'minimal', label: 'As few rest days as possible' },
    ],
  },
  {
    id: 'liftExperience',
    section: 'fitness',
    type: 'multi',
    title: 'Experience with key lifts',
    subtitle: 'Select all that apply',
    options: [
      { value: 'deadlift_new', label: 'New to deadlift' },
      { value: 'squat_new', label: 'New to squat' },
      { value: 'bench_new', label: 'New to bench press' },
      { value: 'deadlift_ok', label: 'Comfortable deadlifting' },
      { value: 'squat_ok', label: 'Comfortable squatting' },
      { value: 'bench_ok', label: 'Comfortable benching' },
    ],
  },
  {
    id: 'foodAllergies',
    section: 'health',
    type: 'multi',
    title: 'Food allergies or intolerances',
    options: [
      { value: 'none', label: 'None' },
      { value: 'nuts', label: 'Nuts' },
      { value: 'gluten', label: 'Gluten' },
      { value: 'lactose', label: 'Lactose / dairy' },
      { value: 'shellfish', label: 'Shellfish' },
      { value: 'eggs', label: 'Eggs' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'foodsExcluded',
    section: 'health',
    type: 'catalogPicker',
    title: 'Foods you never want in your plan',
    subtitle: 'Search our food library',
    field: 'foodsExcluded',
    catalog: 'food',
    multi: true,
    maxSelect: 15,
    optional: true,
    searchHints: [
      { label: 'Pork', query: 'pork' },
      { label: 'Shellfish', query: 'shrimp' },
      { label: 'Peanuts', query: 'peanut' },
    ],
    chatMessage: 'Anything you never want on your plate? Pick foods to exclude — or skip if nothing.',
  },
  {
    id: 'dietType',
    section: 'health',
    type: 'single',
    title: 'Preferred diet style',
    autoAdvance: true,
    options: [
      { value: 'balanced', label: 'Balanced' },
      { value: 'high_protein', label: 'High protein' },
      { value: 'low_carb', label: 'Lower carb' },
      { value: 'mediterranean', label: 'Mediterranean' },
      { value: 'vegetarian', label: 'Vegetarian' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'mealPlanStyle',
    section: 'health',
    type: 'single',
    title: 'Meal plan style',
    autoAdvance: true,
    options: [
      { value: 'fixed_weekly', label: 'Same meals each week' },
      { value: 'rotating_daily', label: 'Rotating daily meals' },
    ],
  },
  {
    id: 'mealsPerDay',
    section: 'health',
    type: 'single',
    title: 'Meals per day',
    autoAdvance: true,
    options: [
      { value: '3', label: '3 meals' },
      { value: '4', label: '4 meals' },
      { value: '5', label: '5 meals' },
      { value: '6', label: '6 meals' },
    ],
  },
  {
    id: 'proteinPrefs',
    section: 'health',
    type: 'catalogPicker',
    title: 'Preferred proteins',
    subtitle: 'Pick what you enjoy eating',
    field: 'proteinPrefs',
    catalog: 'food',
    multi: true,
    maxSelect: 10,
    categoryId: 'poultry-products',
    searchHints: [
      { label: 'Chicken', query: 'chicken', categoryId: 'poultry-products' },
      { label: 'Beef', query: 'beef', categoryId: 'beef' },
      { label: 'Fish', query: 'fish', categoryId: 'finfish-and-shellfish-products' },
      { label: 'Eggs', query: 'egg', categoryId: 'dairy-and-egg-product' },
    ],
    chatMessage: 'What proteins do you like? Tap your go-to foods from the library.',
  },
  {
    id: 'carbPrefs',
    section: 'health',
    type: 'catalogPicker',
    title: 'Preferred carbs',
    subtitle: 'Grains, pasta, and starchy sides',
    field: 'carbPrefs',
    catalog: 'food',
    multi: true,
    maxSelect: 10,
    categoryId: 'cereal-grains-and-pasta',
    searchHints: [
      { label: 'Rice', query: 'rice' },
      { label: 'Oats', query: 'oat' },
      { label: 'Potato', query: 'potato', categoryId: 'vegetables' },
      { label: 'Pasta', query: 'pasta' },
    ],
    chatMessage: 'Which carbs fit your lifestyle? Pick your staples.',
  },
  {
    id: 'fatPrefs',
    section: 'health',
    type: 'catalogPicker',
    title: 'Preferred healthy fats',
    subtitle: 'Oils, nuts, and rich add-ons',
    field: 'fatPrefs',
    catalog: 'food',
    multi: true,
    maxSelect: 10,
    categoryId: 'fats-and-oils',
    searchHints: [
      { label: 'Olive oil', query: 'olive oil' },
      { label: 'Avocado', query: 'avocado', categoryId: 'fruits-and-fruit-juices' },
      { label: 'Nuts', query: 'almond', categoryId: 'nut-and-seed-products' },
      { label: 'Peanut butter', query: 'peanut butter' },
    ],
    chatMessage: 'Healthy fats you actually enjoy — pick a few.',
  },
  {
    id: 'fruitPrefs',
    section: 'health',
    type: 'catalogPicker',
    title: 'Preferred fruits',
    subtitle: 'Sweet picks for snacks and meals',
    field: 'fruitPrefs',
    catalog: 'food',
    multi: true,
    maxSelect: 10,
    categoryId: 'fruits-and-fruit-juices',
    searchHints: [
      { label: 'Banana', query: 'banana' },
      { label: 'Apple', query: 'apple' },
      { label: 'Berries', query: 'berry' },
      { label: 'Dates', query: 'date' },
    ],
    chatMessage: 'Favorite fruits? Browse and tap what you reach for most.',
  },
  {
    id: 'dairyPrefs',
    section: 'health',
    type: 'catalogPicker',
    title: 'Preferred dairy',
    subtitle: 'Milk, yogurt, cheese — or skip',
    field: 'dairyPrefs',
    catalog: 'food',
    multi: true,
    maxSelect: 8,
    optional: true,
    categoryId: 'dairy-and-egg-product',
    searchHints: [
      { label: 'Milk', query: 'milk' },
      { label: 'Yogurt', query: 'yogurt' },
      { label: 'Cheese', query: 'cheese' },
    ],
    chatMessage: 'Dairy you like — or skip if you avoid it.',
  },
  {
    id: 'supplementsBudget',
    section: 'health',
    type: 'text',
    title: 'Supplements & budget',
    field: 'supplementsBudget',
    placeholder: 'What you use now and what you can buy',
    maxLength: 400,
  },
  {
    id: 'foodBudget',
    section: 'health',
    type: 'single',
    title: 'Food budget',
    autoAdvance: true,
    options: [
      { value: 'low', label: 'Low' },
      { value: 'medium', label: 'Medium' },
      { value: 'high', label: 'High' },
    ],
  },
  {
    id: 'mealPrepTime',
    section: 'health',
    type: 'single',
    title: 'Time to prepare meals',
    autoAdvance: true,
    options: [
      { value: '5', label: '~5 minutes' },
      { value: '30', label: '~30 minutes' },
      { value: '60', label: '1 hour+' },
    ],
  },
  {
    id: 'cookOrReady',
    section: 'health',
    type: 'single',
    title: 'Cooking vs ready meals',
    autoAdvance: true,
    options: [
      { value: 'cook', label: 'I cook' },
      { value: 'ready', label: 'Mostly ready / delivery' },
      { value: 'mixed', label: 'Mixed' },
    ],
  },
  {
    id: 'religiousDiet',
    section: 'health',
    type: 'multi',
    title: 'Religious or cultural diet rules',
    options: [
      { value: 'none', label: 'None' },
      { value: 'halal', label: 'Halal' },
      { value: 'ramadan', label: 'Ramadan fasting' },
      { value: 'vegan_strict', label: 'Strict vegetarian/vegan' },
    ],
  },
  {
    id: 'calorieTarget',
    section: 'health',
    type: 'single',
    title: 'Calorie target',
    autoAdvance: true,
    options: [
      { value: 'coach', label: 'Coach decides' },
      { value: 'deficit_aggressive', label: 'Aggressive cut' },
      { value: 'deficit_mild', label: 'Mild cut' },
      { value: 'maintain', label: 'Maintain' },
      { value: 'surplus', label: 'Muscle gain surplus' },
    ],
  },
  {
    id: 'medicalHistory',
    section: 'health',
    type: 'text',
    title: 'Medical history',
    field: 'medicalHistory',
    placeholder: 'Conditions, surgeries, chronic issues…',
    maxLength: 500,
  },
  {
    id: 'medications',
    section: 'health',
    type: 'text',
    title: 'Current medications',
    field: 'medications',
    placeholder: 'List medications affecting weight/training',
    maxLength: 400,
  },
  {
    id: 'pastInjuriesHistory',
    section: 'health',
    type: 'multi',
    title: 'Past injuries (recovered)',
    options: [
      { value: 'none', label: 'None' },
      { value: 'back', label: 'Back', imageUrl: ASSETS.injuryBack },
      { value: 'knees', label: 'Knees', imageUrl: ASSETS.injuryKnees },
      { value: 'shoulders', label: 'Shoulders', imageUrl: ASSETS.injuryShoulders },
      { value: 'neck', label: 'Neck', imageUrl: ASSETS.injuryNeck },
      { value: 'arms', label: 'Arms', imageUrl: ASSETS.injuryArms },
      { value: 'legs', label: 'Legs', imageUrl: ASSETS.injuryLegs },
    ],
  },
  {
    id: 'doctorClearance',
    section: 'health',
    type: 'single',
    title: 'Doctor clearance for exercise?',
    autoAdvance: true,
    options: [
      { value: 'yes', label: 'Yes' },
      { value: 'no', label: 'No' },
      { value: 'not_needed', label: 'Not needed' },
    ],
  },
  {
    id: 'progressTracking',
    section: 'mindset',
    type: 'multi',
    title: 'How do you notice progress?',
    options: [
      { value: 'mirror', label: 'Mirror / photos' },
      { value: 'scale', label: 'Scale' },
      { value: 'strength', label: 'Strength numbers' },
      { value: 'energy', label: 'Energy & mood' },
      { value: 'measurements', label: 'Measurements' },
      { value: 'comments', label: 'Comments from others' },
    ],
  },
  {
    id: 'hungerScale',
    section: 'mindset',
    type: 'single',
    title: 'Average daily hunger (1–10)',
    autoAdvance: true,
    options: [
      { value: '1', label: '1' },
      { value: '2', label: '2' },
      { value: '3', label: '3' },
      { value: '4', label: '4' },
      { value: '5', label: '5' },
      { value: '6', label: '6' },
      { value: '7', label: '7' },
      { value: '8', label: '8' },
      { value: '9', label: '9' },
      { value: '10', label: '10' },
    ],
  },
  {
    id: 'motivationStart',
    section: 'mindset',
    type: 'multi',
    title: 'What made you want to start?',
    subtitle: 'Select all that apply',
    options: [
      { value: 'visual', label: 'Mirror / scale', description: 'Visual change' },
      { value: 'fitness', label: 'Fitness level', description: 'Want to improve' },
      { value: 'health', label: 'Health' },
      { value: 'clothing', label: 'Clothing fit' },
      { value: 'aging', label: 'Aging' },
    ],
  },
];
