import type { OnboardingStep } from '../types';
import { ASSETS } from '../onboardingAssets';

/** Steps added for multi-flow questionnaires (not in legacy RAW list). */
export const EXTRA_QUESTIONNAIRE_STEPS: OnboardingStep[] = [
  {
    id: 'bodyMeasurements',
    section: 'profile',
    type: 'measurements',
    title: 'Body measurements (optional)',
    subtitle: 'Chest, waist, hips — helps track progress',
    presentation: 'chat',
  },
  {
    id: 'activityLevel',
    section: 'profile',
    type: 'single',
    title: 'Daily activity level',
    subtitle: 'Outside the gym — affects calories and recovery',
    autoAdvance: true,
    options: [
      { value: 'sedentary', label: 'Mostly sitting', description: 'Desk job, little walking' },
      { value: 'light', label: 'Light', description: 'Some walking' },
      { value: 'moderate', label: 'Moderate', description: 'On feet part of the day' },
      { value: 'active', label: 'Active', description: 'Physical job or lots of movement' },
      { value: 'very_active', label: 'Very active', description: 'Highly physical daily life' },
    ],
  },
  {
    id: 'lastTraining',
    section: 'profile',
    type: 'single',
    title: 'Last consistent training',
    autoAdvance: true,
    options: [
      { value: 'never', label: 'Never trained regularly' },
      { value: 'under_3m', label: 'Stopped under 3 months ago' },
      { value: '3_12m', label: '3–12 months ago' },
      { value: 'over_1y', label: 'Over a year ago but experienced' },
      { value: 'current', label: 'Training now' },
    ],
  },
  {
    id: 'inbodyScan',
    section: 'profile',
    type: 'inbody',
    title: 'InBody scan',
    subtitle: 'Optional fields — required to finish this section',
    requireComplete: true,
  },
  {
    id: 'progressPhotos',
    section: 'profile',
    type: 'photos',
    title: 'Progress photos',
    subtitle: 'Front and back — required to finish this section',
    requireComplete: true,
  },
  {
    id: 'goal12Week',
    section: 'training',
    type: 'text',
    title: '12-week training goal',
    field: 'goal12Week',
    placeholder: 'e.g. lose 5 kg fat, add strength on bench…',
    minLength: 3,
    maxLength: 200,
  },
  {
    id: 'trainingDaysPerWeek',
    section: 'training',
    type: 'single',
    title: 'Training days per week',
    autoAdvance: true,
    options: [
      { value: '2', label: '2 days' },
      { value: '3', label: '3 days' },
      { value: '4', label: '4 days' },
      { value: '5', label: '5 days' },
      { value: '6', label: '6 days' },
    ],
  },
  {
    id: 'gymLink',
    section: 'training',
    type: 'text',
    title: 'Link your gym',
    field: 'gymLink',
    placeholder: 'Gym name or ID from Taqwin gyms list',
    minLength: 2,
    maxLength: 120,
  },
  {
    id: 'preferredSplit',
    section: 'training',
    type: 'single',
    title: 'Preferred split / schedule',
    autoAdvance: true,
    options: [
      { value: 'full_body', label: 'Full body' },
      { value: 'upper_lower', label: 'Upper / lower' },
      { value: 'ppl', label: 'Push / pull / legs' },
      { value: 'bro', label: 'Bro split' },
      { value: 'coach', label: 'Let the coach decide' },
    ],
  },
  {
    id: 'exercisesAvoid',
    section: 'training',
    type: 'text',
    title: 'Exercises to avoid',
    field: 'exercisesAvoid',
    placeholder: 'e.g. burpees, leg press…',
    maxLength: 300,
  },
  {
    id: 'exercisesLove',
    section: 'training',
    type: 'text',
    title: 'Exercises you want included',
    field: 'exercisesLove',
    placeholder: 'e.g. bench press, rows…',
    maxLength: 300,
  },
  {
    id: 'pullups',
    section: 'fitness',
    type: 'single',
    title: 'How many pull-ups can you do?',
    autoAdvance: true,
    options: [
      { value: '0', label: 'None yet' },
      { value: 'lt5', label: '1–5' },
      { value: '6_12', label: '6–12' },
      { value: 'gt12', label: 'More than 12' },
      { value: 'unknown', label: "I don't know" },
    ],
  },
  {
    id: 'strengthEquipment',
    section: 'training',
    type: 'multi',
    title: 'Strength equipment available',
    options: [
      { value: 'barbell', label: 'Barbell & rack' },
      { value: 'dumbbells', label: 'Dumbbells' },
      { value: 'cables', label: 'Cable machines' },
      { value: 'machines', label: 'Plate machines' },
      { value: 'kettlebells', label: 'Kettlebells' },
      { value: 'bands', label: 'Resistance bands' },
      { value: 'bodyweight', label: 'Bodyweight only' },
    ],
  },
  {
    id: 'goal12WeekPace',
    section: 'training',
    type: 'single',
    title: '12-week goal intensity',
    autoAdvance: true,
    options: [
      { value: 'fast', label: 'As fast as possible' },
      { value: 'balanced', label: 'Balanced' },
      { value: 'calm', label: 'Slow and steady' },
    ],
  },
  {
    id: 'restDaysPreference',
    section: 'training',
    type: 'single',
    title: 'Rest days',
    autoAdvance: true,
    options: [
      { value: 'fixed', label: 'I want fixed rest days' },
      { value: 'coach', label: 'Coach decides' },
      { value: 'minimal', label: 'As few rest days as possible' },
    ],
  },
  {
    id: 'liftExperience',
    section: 'fitness',
    type: 'multi',
    title: 'Experience with key lifts',
    subtitle: 'Select all that apply',
    options: [
      { value: 'deadlift_new', label: 'New to deadlift' },
      { value: 'squat_new', label: 'New to squat' },
      { value: 'bench_new', label: 'New to bench press' },
      { value: 'deadlift_ok', label: 'Comfortable deadlifting' },
      { value: 'squat_ok', label: 'Comfortable squatting' },
      { value: 'bench_ok', label: 'Comfortable benching' },
    ],
  },
  {
    id: 'foodAllergies',
    section: 'health',
    type: 'multi',
    title: 'Food allergies or intolerances',
    options: [
      { value: 'none', label: 'None' },
      { value: 'nuts', label: 'Nuts' },
      { value: 'gluten', label: 'Gluten' },
      { value: 'lactose', label: 'Lactose / dairy' },
      { value: 'shellfish', label: 'Shellfish' },
      { value: 'eggs', label: 'Eggs' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'foodsExcluded',
    section: 'health',
    type: 'text',
    title: 'Foods you never want in your plan',
    field: 'foodsExcluded',
    placeholder: 'List any foods to exclude',
    maxLength: 400,
  },
  {
    id: 'dietType',
    section: 'health',
    type: 'single',
    title: 'Preferred diet style',
    autoAdvance: true,
    options: [
      { value: 'balanced', label: 'Balanced' },
      { value: 'high_protein', label: 'High protein' },
      { value: 'low_carb', label: 'Lower carb' },
      { value: 'mediterranean', label: 'Mediterranean' },
      { value: 'vegetarian', label: 'Vegetarian' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'mealPlanStyle',
    section: 'health',
    type: 'single',
    title: 'Meal plan style',
    autoAdvance: true,
    options: [
      { value: 'fixed_weekly', label: 'Same meals each week' },
      { value: 'rotating_daily', label: 'Rotating daily meals' },
    ],
  },
  {
    id: 'mealsPerDay',
    section: 'health',
    type: 'single',
    title: 'Meals per day',
    autoAdvance: true,
    options: [
      { value: '3', label: '3 meals' },
      { value: '4', label: '4 meals' },
      { value: '5', label: '5 meals' },
      { value: '6', label: '6 meals' },
    ],
  },
  {
    id: 'proteinPrefs',
    section: 'health',
    type: 'multi',
    title: 'Preferred proteins',
    options: [
      { value: 'beef', label: 'Beef' },
      { value: 'chicken', label: 'Chicken' },
      { value: 'fish', label: 'Fish' },
      { value: 'tuna', label: 'Tuna' },
      { value: 'salmon', label: 'Salmon' },
      { value: 'beef_liver', label: 'Beef liver' },
      { value: 'chicken_liver', label: 'Chicken liver' },
      { value: 'eggs', label: 'Eggs' },
    ],
  },
  {
    id: 'carbPrefs',
    section: 'health',
    type: 'multi',
    title: 'Preferred carbs',
    options: [
      { value: 'rice', label: 'Rice' },
      { value: 'potatoes', label: 'Potatoes' },
      { value: 'sweet_potato', label: 'Sweet potato' },
      { value: 'brown_pasta', label: 'Brown pasta' },
      { value: 'oats', label: 'Oats' },
      { value: 'quinoa', label: 'Quinoa' },
      { value: 'brown_toast', label: 'Brown toast' },
    ],
  },
  {
    id: 'fatPrefs',
    section: 'health',
    type: 'multi',
    title: 'Preferred healthy fats',
    options: [
      { value: 'olive_oil', label: 'Olive oil' },
      { value: 'coconut_oil', label: 'Coconut oil' },
      { value: 'butter', label: 'Butter' },
      { value: 'egg_yolk', label: 'Egg yolks' },
      { value: 'nuts', label: 'Nuts' },
      { value: 'avocado', label: 'Avocado' },
      { value: 'peanut_butter', label: 'Peanut butter' },
    ],
  },
  {
    id: 'fruitPrefs',
    section: 'health',
    type: 'multi',
    title: 'Preferred fruits',
    options: [
      { value: 'banana', label: 'Banana' },
      { value: 'apple', label: 'Apple' },
      { value: 'berries', label: 'Berries' },
      { value: 'dates', label: 'Dates' },
      { value: 'citrus', label: 'Citrus' },
      { value: 'tropical', label: 'Tropical' },
    ],
  },
  {
    id: 'dairyPrefs',
    section: 'health',
    type: 'multi',
    title: 'Preferred dairy',
    options: [
      { value: 'milk', label: 'Milk' },
      { value: 'yogurt', label: 'Yogurt' },
      { value: 'cheese', label: 'Cheese' },
      { value: 'none', label: 'No dairy' },
    ],
  },
  {
    id: 'supplementsBudget',
    section: 'health',
    type: 'text',
    title: 'Supplements & budget',
    field: 'supplementsBudget',
    placeholder: 'What you use now and what you can buy',
    maxLength: 400,
  },
  {
    id: 'foodBudget',
    section: 'health',
    type: 'single',
    title: 'Food budget',
    autoAdvance: true,
    options: [
      { value: 'low', label: 'Low' },
      { value: 'medium', label: 'Medium' },
      { value: 'high', label: 'High' },
    ],
  },
  {
    id: 'mealPrepTime',
    section: 'health',
    type: 'single',
    title: 'Time to prepare meals',
    autoAdvance: true,
    options: [
      { value: '5', label: '~5 minutes' },
      { value: '30', label: '~30 minutes' },
      { value: '60', label: '1 hour+' },
    ],
  },
  {
    id: 'cookOrReady',
    section: 'health',
    type: 'single',
    title: 'Cooking vs ready meals',
    autoAdvance: true,
    options: [
      { value: 'cook', label: 'I cook' },
      { value: 'ready', label: 'Mostly ready / delivery' },
      { value: 'mixed', label: 'Mixed' },
    ],
  },
  {
    id: 'religiousDiet',
    section: 'health',
    type: 'multi',
    title: 'Religious or cultural diet rules',
    options: [
      { value: 'none', label: 'None' },
      { value: 'halal', label: 'Halal' },
      { value: 'ramadan', label: 'Ramadan fasting' },
      { value: 'vegan_strict', label: 'Strict vegetarian/vegan' },
    ],
  },
  {
    id: 'calorieTarget',
    section: 'health',
    type: 'single',
    title: 'Calorie target',
    autoAdvance: true,
    options: [
      { value: 'coach', label: 'Coach decides' },
      { value: 'deficit_aggressive', label: 'Aggressive cut' },
      { value: 'deficit_mild', label: 'Mild cut' },
      { value: 'maintain', label: 'Maintain' },
      { value: 'surplus', label: 'Muscle gain surplus' },
    ],
  },
  {
    id: 'medicalHistory',
    section: 'health',
    type: 'text',
    title: 'Medical history',
    field: 'medicalHistory',
    placeholder: 'Conditions, surgeries, chronic issues…',
    maxLength: 500,
  },
  {
    id: 'medications',
    section: 'health',
    type: 'text',
    title: 'Current medications',
    field: 'medications',
    placeholder: 'List medications affecting weight/training',
    maxLength: 400,
  },
  {
    id: 'pastInjuriesHistory',
    section: 'health',
    type: 'multi',
    title: 'Past injuries (recovered)',
    options: [
      { value: 'none', label: 'None' },
      { value: 'back', label: 'Back', imageUrl: ASSETS.injuryBack },
      { value: 'knees', label: 'Knees', imageUrl: ASSETS.injuryKnees },
      { value: 'shoulders', label: 'Shoulders', imageUrl: ASSETS.injuryShoulders },
      { value: 'neck', label: 'Neck', imageUrl: ASSETS.injuryNeck },
      { value: 'arms', label: 'Arms', imageUrl: ASSETS.injuryArms },
      { value: 'legs', label: 'Legs', imageUrl: ASSETS.injuryLegs },
    ],
  },
  {
    id: 'doctorClearance',
    section: 'health',
    type: 'single',
    title: 'Doctor clearance for exercise?',
    autoAdvance: true,
    options: [
      { value: 'yes', label: 'Yes' },
      { value: 'no', label: 'No' },
      { value: 'not_needed', label: 'Not needed' },
    ],
  },
  {
    id: 'progressTracking',
    section: 'mindset',
    type: 'multi',
    title: 'How do you notice progress?',
    options: [
      { value: 'mirror', label: 'Mirror / photos' },
      { value: 'scale', label: 'Scale' },
      { value: 'strength', label: 'Strength numbers' },
      { value: 'energy', label: 'Energy & mood' },
      { value: 'measurements', label: 'Measurements' },
      { value: 'comments', label: 'Comments from others' },
    ],
  },
  {
    id: 'hungerScale',
    section: 'mindset',
    type: 'single',
    title: 'Average daily hunger (1–10)',
    autoAdvance: true,
    options: [
      { value: '1', label: '1' },
      { value: '2', label: '2' },
      { value: '3', label: '3' },
      { value: '4', label: '4' },
      { value: '5', label: '5' },
      { value: '6', label: '6' },
      { value: '7', label: '7' },
      { value: '8', label: '8' },
      { value: '9', label: '9' },
      { value: '10', label: '10' },
    ],
  },
  {
    id: 'motivationStart',
    section: 'mindset',
    type: 'multi',
    title: 'What made you want to start?',
    subtitle: 'Select all that apply',
    options: [
      { value: 'visual', label: 'Mirror / scale', description: 'Visual change' },
      { value: 'fitness', label: 'Fitness level', description: 'Want to improve' },
      { value: 'health', label: 'Health' },
      { value: 'clothing', label: 'Clothing fit' },
      { value: 'aging', label: 'Aging' },
    ],
  },
];
