import type { OnboardingStep, StepOption } from '../types';

const PREFER_NOT_TO_SAY: StepOption = { value: 'prefer_not_to_say', label: 'Prefer not to say' };

/** Optional female-health steps (Level 1 + Level 2). Shown only when needsFemaleWellness. */
export const FEMALE_HEALTH_STEP_IDS = [
  'femaleHealthIntro',
  'cycleRegularity',
  'cycleSymptoms',
  'pregnancyStatus',
  'postpartumStatus',
  'breastfeeding',
  'femaleHealthConditions',
  'birthControl',
  'menopause',
  'cycleLength',
] as const;

export type FemaleHealthStepId = (typeof FEMALE_HEALTH_STEP_IDS)[number];

export const FEMALE_HEALTH_STEPS: OnboardingStep[] = [
  {
    id: 'femaleHealthIntro',
    section: 'femaleHealth',
    type: 'info',
    title: 'Female health — optional',
    body: 'These questions are optional and private. Skip anything you prefer not to share — you can update your answers later anytime.',
    highlight: 'Optional · Private · Skip anytime',
    cta: 'Continue',
    optional: true,
  },
  {
    id: 'cycleRegularity',
    section: 'femaleHealth',
    type: 'single',
    title: 'Is your menstrual cycle regular?',
    subtitle: 'Optional — helps us interpret energy and recovery patterns',
    visualOptions: false,
    autoAdvance: true,
    optional: true,
    options: [
      { value: 'regular', label: 'Regular' },
      { value: 'irregular', label: 'Irregular' },
      { value: 'not_sure', label: 'Not sure' },
      PREFER_NOT_TO_SAY,
    ],
  },
  {
    id: 'cycleSymptoms',
    section: 'femaleHealth',
    type: 'multi',
    title: 'Which symptoms do you usually experience?',
    subtitle: 'Optional — select all that apply',
    visualOptions: false,
    optional: true,
    options: [
      { value: 'fatigue', label: 'Fatigue' },
      { value: 'bloating', label: 'Bloating' },
      { value: 'cravings', label: 'Cravings' },
      { value: 'mood_changes', label: 'Mood changes' },
      { value: 'cramps', label: 'Cramps' },
      { value: 'headaches', label: 'Headaches' },
      { value: 'none', label: 'None' },
    ],
  },
  {
    id: 'pregnancyStatus',
    section: 'femaleHealth',
    type: 'single',
    title: 'Are you currently pregnant?',
    visualOptions: false,
    autoAdvance: true,
    optional: true,
    options: [
      { value: 'yes', label: 'Yes' },
      { value: 'no', label: 'No' },
      PREFER_NOT_TO_SAY,
    ],
  },
  {
    id: 'postpartumStatus',
    section: 'femaleHealth',
    type: 'single',
    title: 'Are you postpartum?',
    visualOptions: false,
    autoAdvance: true,
    optional: true,
    options: [
      { value: 'no', label: 'No' },
      { value: 'lt_6m', label: 'Less than 6 months' },
      { value: '6_12m', label: '6–12 months' },
      { value: 'gt_12m', label: 'More than 12 months' },
      PREFER_NOT_TO_SAY,
    ],
  },
  {
    id: 'breastfeeding',
    section: 'femaleHealth',
    type: 'single',
    title: 'Are you breastfeeding?',
    visualOptions: false,
    autoAdvance: true,
    optional: true,
    options: [
      { value: 'yes', label: 'Yes' },
      { value: 'no', label: 'No' },
    ],
  },
  {
    id: 'femaleHealthConditions',
    section: 'femaleHealth',
    type: 'multi',
    title: 'Do you have any of these conditions?',
    subtitle: 'Optional — not a diagnosis; helps personalize recovery and nutrition',
    visualOptions: false,
    optional: true,
    options: [
      { value: 'pcos', label: 'PCOS' },
      { value: 'thyroid', label: 'Thyroid disorder' },
      { value: 'anemia', label: 'Anemia' },
      { value: 'insulin_resistance', label: 'Insulin resistance' },
      { value: 'endometriosis', label: 'Endometriosis' },
      { value: 'none', label: 'None' },
      PREFER_NOT_TO_SAY,
    ],
  },
  {
    id: 'birthControl',
    section: 'femaleHealth',
    type: 'single',
    title: 'Do you use hormonal birth control?',
    visualOptions: false,
    autoAdvance: true,
    optional: true,
    options: [
      { value: 'yes', label: 'Yes' },
      { value: 'no', label: 'No' },
      PREFER_NOT_TO_SAY,
    ],
  },
  {
    id: 'menopause',
    section: 'femaleHealth',
    type: 'single',
    title: 'Are you in menopause?',
    subtitle: 'Optional',
    visualOptions: false,
    autoAdvance: true,
    optional: true,
    options: [
      { value: 'yes', label: 'Yes' },
      { value: 'perimenopause', label: 'Perimenopause' },
      { value: 'no', label: 'No' },
      PREFER_NOT_TO_SAY,
    ],
  },
  {
    id: 'cycleLength',
    section: 'femaleHealth',
    type: 'single',
    title: 'Average cycle length?',
    visualOptions: false,
    autoAdvance: true,
    optional: true,
    options: [
      { value: '21_24', label: '21–24 days' },
      { value: '25_30', label: '25–30 days' },
      { value: '31_35', label: '31–35 days' },
      { value: 'irregular', label: 'Irregular' },
      PREFER_NOT_TO_SAY,
    ],
  },
];
